/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */

export interface ApiAdminUpdateUserRequest {
  active?: boolean
  /** @minLength 1 */
  first_name?: string
  /** @minLength 1 */
  last_name?: string
}
