/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import type { ApiAdminCreateUserRequestRole } from './apiAdminCreateUserRequestRole'

export interface ApiAdminCreateUserRequest {
  active?: boolean
  email: string
  /** @minLength 1 */
  first_name?: string
  /** @minLength 1 */
  last_name?: string
  /** @minLength 8 */
  password: string
  role: ApiAdminCreateUserRequestRole
}
