/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */

export type ApiAdminCreateUserRequestRole =
  (typeof ApiAdminCreateUserRequestRole)[keyof typeof ApiAdminCreateUserRequestRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiAdminCreateUserRequestRole = {
  customer: 'customer',
  employee: 'employee',
  admin: 'admin',
} as const
