/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */

export interface ApiChangePasswordRequest {
  /** @minLength 8 */
  new_password: string
  old_password: string
}
