/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */

export interface ApiTokenResponse {
  access_token?: string
  /** seconds */
  expires_in?: number
  refresh_token?: string
}
