/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */

export interface RequestPaginatedResponse {
  data?: unknown
  limit?: number
  offset?: number
  total?: number
}
