/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import type { RequestPaginatedResponse } from './requestPaginatedResponse'
import type { UsersList200AllOf } from './usersList200AllOf'

export type UsersList200 = RequestPaginatedResponse & UsersList200AllOf
