/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */

export type UsersListParams = {
  /**
   * Limit the number of responses
   */
  limit?: number
  /**
   * Offset the first response
   */
  offset?: number
  /**
   * Sort results
   */
  sort?: string
}
