/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ApiPurchaseRequestType } from './apiPurchaseRequestType'

export interface ApiPurchaseRequest {
  /** @minimum 1 */
  count: number
  /** @minLength 3 */
  name: string
  /** @minimum 0 */
  price_per_item_cents: number
  type: ApiPurchaseRequestType
}
