/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ModelsPurchaseType } from './modelsPurchaseType'

export interface ApiPurchaseResponse {
  count?: number
  created_at?: string
  id?: string
  name?: string
  price_per_item_cents?: number
  type?: ModelsPurchaseType
  updated_at?: string
}
