/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export type ApiPurchaseRequestType =
  (typeof ApiPurchaseRequestType)[keyof typeof ApiPurchaseRequestType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiPurchaseRequestType = {
  FOOD: 'FOOD',
  DRINK: 'DRINK',
  SNACK: 'SNACK',
} as const
