/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ApiReservationRequestType } from './apiReservationRequestType'

export interface ApiReservationRequest {
  /** @minimum 1 */
  col: number
  room_id: string
  /** @minimum 1 */
  row: number
  theater_id: string
  time_slot_id: string
  type: ApiReservationRequestType
}
