/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ModelsReservationType } from './modelsReservationType'

export interface ApiReservationResponse {
  col?: number
  created_at?: string
  id?: string
  row?: number
  time_slot_id?: string
  type?: ModelsReservationType
  updated_at?: string
  user_id?: string
}
