/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export type ModelsReservationType =
  (typeof ModelsReservationType)[keyof typeof ModelsReservationType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsReservationType = {
  Online: 'ONLINE',
  Pos: 'POS',
} as const
