/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export type ModelsPurchaseType = (typeof ModelsPurchaseType)[keyof typeof ModelsPurchaseType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsPurchaseType = {
  Food: 'FOOD',
  Drink: 'DRINK',
  Snack: 'SNACK',
} as const
