/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { RequestPaginatedResponse } from './requestPaginatedResponse'
import type { MyReservationsList200AllOf } from './myReservationsList200AllOf'

export type MyReservationsList200 = RequestPaginatedResponse & MyReservationsList200AllOf
