/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ApiPurchaseResponse } from './apiPurchaseResponse'

export type PurchasesList200AllOf = {
  data?: ApiPurchaseResponse[]
}
