/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export interface RequestPaginatedResponse {
  data?: unknown
  limit?: number
  offset?: number
  total?: number
}
