/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiChangePasswordRequest,
  ApiLoginRequest,
  ApiRegisterRequest,
  ApiTokenResponse,
  ApiUpdateUserRequest,
  ApiUserResponse,
  ChangePassword200,
  MiddlewareHttpError,
  RefreshTokenBody,
  VerifyTokenBody,
} from '.././model'

import { authMutator } from '../../auth-mutator'

/**
 * Authenticate user and return JWT tokens
 * @summary Login user
 */
export const login = (apiLoginRequest: MaybeRef<ApiLoginRequest>, signal?: AbortSignal) => {
  apiLoginRequest = unref(apiLoginRequest)

  return authMutator<ApiTokenResponse>({
    url: `/api/v1/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiLoginRequest,
    signal,
  })
}

export const getLoginMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: ApiLoginRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: ApiLoginRequest },
  TContext
> => {
  const mutationKey = ['login']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: ApiLoginRequest }
  > = (props) => {
    const { data } = props ?? {}

    return login(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginMutationBody = ApiLoginRequest
export type LoginMutationError = MiddlewareHttpError

/**
 * @summary Login user
 */
export const useLogin = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      { data: ApiLoginRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: ApiLoginRequest },
  TContext
> => {
  const mutationOptions = getLoginMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get information about the currently authenticated user
 * @summary Get current user
 */
export const getCurrentUser = (signal?: AbortSignal) => {
  return authMutator<ApiUserResponse>({ url: `/api/v1/auth/me`, method: 'GET', signal })
}

export const getGetCurrentUserQueryKey = () => {
  return ['api', 'v1', 'auth', 'me'] as const
}

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = MiddlewareHttpError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getGetCurrentUserQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) =>
    getCurrentUser(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = MiddlewareHttpError

/**
 * @summary Get current user
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = MiddlewareHttpError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update information about the currently authenticated user
 * @summary Update current user
 */
export const updateCurrentUser = (apiUpdateUserRequest: MaybeRef<ApiUpdateUserRequest>) => {
  apiUpdateUserRequest = unref(apiUpdateUserRequest)

  return authMutator<ApiUserResponse>({
    url: `/api/v1/auth/me`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiUpdateUserRequest,
  })
}

export const getUpdateCurrentUserMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    TError,
    { data: ApiUpdateUserRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCurrentUser>>,
  TError,
  { data: ApiUpdateUserRequest },
  TContext
> => {
  const mutationKey = ['updateCurrentUser']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    { data: ApiUpdateUserRequest }
  > = (props) => {
    const { data } = props ?? {}

    return updateCurrentUser(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateCurrentUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrentUser>>
>
export type UpdateCurrentUserMutationBody = ApiUpdateUserRequest
export type UpdateCurrentUserMutationError = MiddlewareHttpError

/**
 * @summary Update current user
 */
export const useUpdateCurrentUser = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCurrentUser>>,
      TError,
      { data: ApiUpdateUserRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateCurrentUser>>,
  TError,
  { data: ApiUpdateUserRequest },
  TContext
> => {
  const mutationOptions = getUpdateCurrentUserMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Change password for the currently authenticated user
 * @summary Change password
 */
export const changePassword = (apiChangePasswordRequest: MaybeRef<ApiChangePasswordRequest>) => {
  apiChangePasswordRequest = unref(apiChangePasswordRequest)

  return authMutator<ChangePassword200>({
    url: `/api/v1/auth/me/password`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiChangePasswordRequest,
  })
}

export const getChangePasswordMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changePassword>>,
    TError,
    { data: ApiChangePasswordRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof changePassword>>,
  TError,
  { data: ApiChangePasswordRequest },
  TContext
> => {
  const mutationKey = ['changePassword']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changePassword>>,
    { data: ApiChangePasswordRequest }
  > = (props) => {
    const { data } = props ?? {}

    return changePassword(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
export type ChangePasswordMutationBody = ApiChangePasswordRequest
export type ChangePasswordMutationError = MiddlewareHttpError

/**
 * @summary Change password
 */
export const useChangePassword = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changePassword>>,
      TError,
      { data: ApiChangePasswordRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof changePassword>>,
  TError,
  { data: ApiChangePasswordRequest },
  TContext
> => {
  const mutationOptions = getChangePasswordMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Use refresh token to get a new access token
 * @summary Refresh access token
 */
export const refreshToken = (
  refreshTokenBody: MaybeRef<RefreshTokenBody>,
  signal?: AbortSignal,
) => {
  refreshTokenBody = unref(refreshTokenBody)

  return authMutator<ApiTokenResponse>({
    url: `/api/v1/auth/refresh`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: refreshTokenBody,
    signal,
  })
}

export const getRefreshTokenMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    { data: RefreshTokenBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  { data: RefreshTokenBody },
  TContext
> => {
  const mutationKey = ['refreshToken']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    { data: RefreshTokenBody }
  > = (props) => {
    const { data } = props ?? {}

    return refreshToken(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
export type RefreshTokenMutationBody = RefreshTokenBody
export type RefreshTokenMutationError = MiddlewareHttpError

/**
 * @summary Refresh access token
 */
export const useRefreshToken = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshToken>>,
      TError,
      { data: RefreshTokenBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  { data: RefreshTokenBody },
  TContext
> => {
  const mutationOptions = getRefreshTokenMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Register a new user account
 * @summary Register a new user
 */
export const register = (
  apiRegisterRequest: MaybeRef<ApiRegisterRequest>,
  signal?: AbortSignal,
) => {
  apiRegisterRequest = unref(apiRegisterRequest)

  return authMutator<ApiUserResponse>({
    url: `/api/v1/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiRegisterRequest,
    signal,
  })
}

export const getRegisterMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: ApiRegisterRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: ApiRegisterRequest },
  TContext
> => {
  const mutationKey = ['register']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: ApiRegisterRequest }
  > = (props) => {
    const { data } = props ?? {}

    return register(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type RegisterMutationBody = ApiRegisterRequest
export type RegisterMutationError = MiddlewareHttpError

/**
 * @summary Register a new user
 */
export const useRegister = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof register>>,
      TError,
      { data: ApiRegisterRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: ApiRegisterRequest },
  TContext
> => {
  const mutationOptions = getRegisterMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Verify a JWT token and return user information
 * @summary Verify JWT token
 */
export const verifyToken = (verifyTokenBody: MaybeRef<VerifyTokenBody>, signal?: AbortSignal) => {
  verifyTokenBody = unref(verifyTokenBody)

  return authMutator<ApiUserResponse>({
    url: `/api/v1/auth/verify`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verifyTokenBody,
    signal,
  })
}

export const getVerifyTokenMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyToken>>,
    TError,
    { data: VerifyTokenBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof verifyToken>>,
  TError,
  { data: VerifyTokenBody },
  TContext
> => {
  const mutationKey = ['verifyToken']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof verifyToken>>,
    { data: VerifyTokenBody }
  > = (props) => {
    const { data } = props ?? {}

    return verifyToken(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type VerifyTokenMutationResult = NonNullable<Awaited<ReturnType<typeof verifyToken>>>
export type VerifyTokenMutationBody = VerifyTokenBody
export type VerifyTokenMutationError = MiddlewareHttpError

/**
 * @summary Verify JWT token
 */
export const useVerifyToken = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof verifyToken>>,
      TError,
      { data: VerifyTokenBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof verifyToken>>,
  TError,
  { data: VerifyTokenBody },
  TContext
> => {
  const mutationOptions = getVerifyTokenMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
