/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiChangePasswordRequest,
  ApiLoginRequest,
  ApiRegisterRequest,
  ApiTokenResponse,
  ApiUpdateUserRequest,
  ApiUserResponse,
  ChangePassword200,
  MiddlewareHttpError,
  RefreshTokenBody,
  VerifyTokenBody,
} from '.././model'

/**
 * Authenticate user and return JWT tokens
 * @summary Login user
 */
export const login = (
  apiLoginRequest: MaybeRef<ApiLoginRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiTokenResponse>> => {
  apiLoginRequest = unref(apiLoginRequest)

  return axios.default.post(`/login`, apiLoginRequest, options)
}

export const getLoginMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: ApiLoginRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: ApiLoginRequest },
  TContext
> => {
  const mutationKey = ['login']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: ApiLoginRequest }
  > = (props) => {
    const { data } = props ?? {}

    return login(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginMutationBody = ApiLoginRequest
export type LoginMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Login user
 */
export const useLogin = <TError = AxiosError<MiddlewareHttpError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: ApiLoginRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: ApiLoginRequest },
  TContext
> => {
  const mutationOptions = getLoginMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Get information about the currently authenticated user
 * @summary Get current user
 */
export const getCurrentUser = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  return axios.default.get(`/me`, options)
}

export const getGetCurrentUserQueryKey = () => {
  return ['me'] as const
}

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = AxiosError<MiddlewareHttpError>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getGetCurrentUserQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) =>
    getCurrentUser({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Get current user
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = AxiosError<MiddlewareHttpError>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
  axios?: AxiosRequestConfig
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update information about the currently authenticated user
 * @summary Update current user
 */
export const updateCurrentUser = (
  apiUpdateUserRequest: MaybeRef<ApiUpdateUserRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  apiUpdateUserRequest = unref(apiUpdateUserRequest)

  return axios.default.put(`/me`, apiUpdateUserRequest, options)
}

export const getUpdateCurrentUserMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    TError,
    { data: ApiUpdateUserRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCurrentUser>>,
  TError,
  { data: ApiUpdateUserRequest },
  TContext
> => {
  const mutationKey = ['updateCurrentUser']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    { data: ApiUpdateUserRequest }
  > = (props) => {
    const { data } = props ?? {}

    return updateCurrentUser(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateCurrentUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrentUser>>
>
export type UpdateCurrentUserMutationBody = ApiUpdateUserRequest
export type UpdateCurrentUserMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update current user
 */
export const useUpdateCurrentUser = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    TError,
    { data: ApiUpdateUserRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof updateCurrentUser>>,
  TError,
  { data: ApiUpdateUserRequest },
  TContext
> => {
  const mutationOptions = getUpdateCurrentUserMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Change password for the currently authenticated user
 * @summary Change password
 */
export const changePassword = (
  apiChangePasswordRequest: MaybeRef<ApiChangePasswordRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ChangePassword200>> => {
  apiChangePasswordRequest = unref(apiChangePasswordRequest)

  return axios.default.put(`/me/password`, apiChangePasswordRequest, options)
}

export const getChangePasswordMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changePassword>>,
    TError,
    { data: ApiChangePasswordRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof changePassword>>,
  TError,
  { data: ApiChangePasswordRequest },
  TContext
> => {
  const mutationKey = ['changePassword']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changePassword>>,
    { data: ApiChangePasswordRequest }
  > = (props) => {
    const { data } = props ?? {}

    return changePassword(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
export type ChangePasswordMutationBody = ApiChangePasswordRequest
export type ChangePasswordMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Change password
 */
export const useChangePassword = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changePassword>>,
    TError,
    { data: ApiChangePasswordRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof changePassword>>,
  TError,
  { data: ApiChangePasswordRequest },
  TContext
> => {
  const mutationOptions = getChangePasswordMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Use refresh token to get a new access token
 * @summary Refresh access token
 */
export const refreshToken = (
  refreshTokenBody: MaybeRef<RefreshTokenBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiTokenResponse>> => {
  refreshTokenBody = unref(refreshTokenBody)

  return axios.default.post(`/refresh`, refreshTokenBody, options)
}

export const getRefreshTokenMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    { data: RefreshTokenBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  { data: RefreshTokenBody },
  TContext
> => {
  const mutationKey = ['refreshToken']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    { data: RefreshTokenBody }
  > = (props) => {
    const { data } = props ?? {}

    return refreshToken(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
export type RefreshTokenMutationBody = RefreshTokenBody
export type RefreshTokenMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Refresh access token
 */
export const useRefreshToken = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    { data: RefreshTokenBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  { data: RefreshTokenBody },
  TContext
> => {
  const mutationOptions = getRefreshTokenMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Register a new user account
 * @summary Register a new user
 */
export const register = (
  apiRegisterRequest: MaybeRef<ApiRegisterRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  apiRegisterRequest = unref(apiRegisterRequest)

  return axios.default.post(`/register`, apiRegisterRequest, options)
}

export const getRegisterMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: ApiRegisterRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: ApiRegisterRequest },
  TContext
> => {
  const mutationKey = ['register']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: ApiRegisterRequest }
  > = (props) => {
    const { data } = props ?? {}

    return register(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type RegisterMutationBody = ApiRegisterRequest
export type RegisterMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Register a new user
 */
export const useRegister = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: ApiRegisterRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: ApiRegisterRequest },
  TContext
> => {
  const mutationOptions = getRegisterMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Verify a JWT token and return user information
 * @summary Verify JWT token
 */
export const verifyToken = (
  verifyTokenBody: MaybeRef<VerifyTokenBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  verifyTokenBody = unref(verifyTokenBody)

  return axios.default.post(`/verify`, verifyTokenBody, options)
}

export const getVerifyTokenMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyToken>>,
    TError,
    { data: VerifyTokenBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof verifyToken>>,
  TError,
  { data: VerifyTokenBody },
  TContext
> => {
  const mutationKey = ['verifyToken']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof verifyToken>>,
    { data: VerifyTokenBody }
  > = (props) => {
    const { data } = props ?? {}

    return verifyToken(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type VerifyTokenMutationResult = NonNullable<Awaited<ReturnType<typeof verifyToken>>>
export type VerifyTokenMutationBody = VerifyTokenBody
export type VerifyTokenMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Verify JWT token
 */
export const useVerifyToken = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyToken>>,
    TError,
    { data: VerifyTokenBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof verifyToken>>,
  TError,
  { data: VerifyTokenBody },
  TContext
> => {
  const mutationOptions = getVerifyTokenMutationOptions(options)

  return useMutation(mutationOptions)
}
