/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

import { ModelsUserRole } from '.././model'
import type { ApiTokenResponse, ApiUserResponse, ChangePassword200 } from '.././model'

export const getLoginResponseMock = (
  overrideResponse: Partial<ApiTokenResponse> = {},
): ApiTokenResponse => ({
  access_token: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  expires_in: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  refresh_token: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getGetCurrentUserResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getUpdateCurrentUserResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getChangePasswordResponseMock = (
  overrideResponse: Partial<ChangePassword200> = {},
): ChangePassword200 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getRefreshTokenResponseMock = (
  overrideResponse: Partial<ApiTokenResponse> = {},
): ApiTokenResponse => ({
  access_token: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  expires_in: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  refresh_token: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getRegisterResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getVerifyTokenResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getLoginMockHandler = (
  overrideResponse?:
    | ApiTokenResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiTokenResponse> | ApiTokenResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/login',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getGetCurrentUserMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/me',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetCurrentUserResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getUpdateCurrentUserMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/me',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateCurrentUserResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getChangePasswordMockHandler = (
  overrideResponse?:
    | ChangePassword200
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ChangePassword200> | ChangePassword200),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/me/password',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getChangePasswordResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getRefreshTokenMockHandler = (
  overrideResponse?:
    | ApiTokenResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiTokenResponse> | ApiTokenResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/refresh',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRefreshTokenResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getRegisterMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/register',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRegisterResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getVerifyTokenMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/verify',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getVerifyTokenResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getAuthMock = () => [
  getLoginMockHandler(),
  getGetCurrentUserMockHandler(),
  getUpdateCurrentUserMockHandler(),
  getChangePasswordMockHandler(),
  getRefreshTokenMockHandler(),
  getRegisterMockHandler(),
  getVerifyTokenMockHandler(),
]
