/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiTimeSlotResponse,
  MiddlewareHttpError,
  TimeSlotsList200,
  TimeSlotsListParams,
} from '.././model'

import { sporedMutator } from '../../spored-mutator'

/**
 * List time slots
 * @summary List time slots
 */
export const timeSlotsList = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
  signal?: AbortSignal,
) => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)
  params = unref(params)

  return sporedMutator<TimeSlotsList200>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms/${roomID}/timeslots`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getTimeSlotsListQueryKey = (
  theaterID?: MaybeRef<string>,
  roomID?: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
) => {
  return [
    'api',
    'v1',
    'spored',
    'theaters',
    theaterID,
    'rooms',
    roomID,
    'timeslots',
    ...(params ? [params] : []),
  ] as const
}

export const getTimeSlotsListQueryOptions = <
  TData = Awaited<ReturnType<typeof timeSlotsList>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof timeSlotsList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getTimeSlotsListQueryKey(theaterID, roomID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof timeSlotsList>>> = ({ signal }) =>
    timeSlotsList(theaterID, roomID, params, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(theaterID) && unref(roomID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof timeSlotsList>>, TError, TData>
}

export type TimeSlotsListQueryResult = NonNullable<Awaited<ReturnType<typeof timeSlotsList>>>
export type TimeSlotsListQueryError = MiddlewareHttpError

/**
 * @summary List time slots
 */

export function useTimeSlotsList<
  TData = Awaited<ReturnType<typeof timeSlotsList>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof timeSlotsList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTimeSlotsListQueryOptions(theaterID, roomID, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Show time slot
 * @summary Show time slot
 */
export const timeSlotsShow = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  timeSlotID: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)
  timeSlotID = unref(timeSlotID)

  return sporedMutator<ApiTimeSlotResponse>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms/${roomID}/timeslots/${timeSlotID}`,
    method: 'GET',
    signal,
  })
}

export const getTimeSlotsShowQueryKey = (
  theaterID?: MaybeRef<string>,
  roomID?: MaybeRef<string>,
  timeSlotID?: MaybeRef<string>,
) => {
  return [
    'api',
    'v1',
    'spored',
    'theaters',
    theaterID,
    'rooms',
    roomID,
    'timeslots',
    timeSlotID,
  ] as const
}

export const getTimeSlotsShowQueryOptions = <
  TData = Awaited<ReturnType<typeof timeSlotsShow>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  timeSlotID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof timeSlotsShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getTimeSlotsShowQueryKey(theaterID, roomID, timeSlotID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof timeSlotsShow>>> = ({ signal }) =>
    timeSlotsShow(theaterID, roomID, timeSlotID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(theaterID) && unref(roomID) && unref(timeSlotID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof timeSlotsShow>>, TError, TData>
}

export type TimeSlotsShowQueryResult = NonNullable<Awaited<ReturnType<typeof timeSlotsShow>>>
export type TimeSlotsShowQueryError = MiddlewareHttpError

/**
 * @summary Show time slot
 */

export function useTimeSlotsShow<
  TData = Awaited<ReturnType<typeof timeSlotsShow>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  timeSlotID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof timeSlotsShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTimeSlotsShowQueryOptions(theaterID, roomID, timeSlotID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
