/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiTimeSlotResponse,
  MiddlewareHttpError,
  TimeSlotsList200,
  TimeSlotsListParams,
} from '.././model'

/**
 * List time slots
 * @summary List time slots
 */
export const timeSlotsList = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TimeSlotsList200>> => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)
  params = unref(params)

  return axios.default.get(`/theaters/${theaterID}/rooms/${roomID}/timeslots`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getTimeSlotsListQueryKey = (
  theaterID?: MaybeRef<string>,
  roomID?: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
) => {
  return ['theaters', theaterID, 'rooms', roomID, 'timeslots', ...(params ? [params] : [])] as const
}

export const getTimeSlotsListQueryOptions = <
  TData = Awaited<ReturnType<typeof timeSlotsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof timeSlotsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getTimeSlotsListQueryKey(theaterID, roomID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof timeSlotsList>>> = ({ signal }) =>
    timeSlotsList(theaterID, roomID, params, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(theaterID) && unref(roomID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof timeSlotsList>>, TError, TData>
}

export type TimeSlotsListQueryResult = NonNullable<Awaited<ReturnType<typeof timeSlotsList>>>
export type TimeSlotsListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List time slots
 */

export function useTimeSlotsList<
  TData = Awaited<ReturnType<typeof timeSlotsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  params?: MaybeRef<TimeSlotsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof timeSlotsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTimeSlotsListQueryOptions(theaterID, roomID, params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Show time slot
 * @summary Show time slot
 */
export const timeSlotsShow = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  timeSlotID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiTimeSlotResponse>> => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)
  timeSlotID = unref(timeSlotID)

  return axios.default.get(
    `/theaters/${theaterID}/rooms/${roomID}/timeslots/${timeSlotID}`,
    options,
  )
}

export const getTimeSlotsShowQueryKey = (
  theaterID?: MaybeRef<string>,
  roomID?: MaybeRef<string>,
  timeSlotID?: MaybeRef<string>,
) => {
  return ['theaters', theaterID, 'rooms', roomID, 'timeslots', timeSlotID] as const
}

export const getTimeSlotsShowQueryOptions = <
  TData = Awaited<ReturnType<typeof timeSlotsShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  timeSlotID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof timeSlotsShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getTimeSlotsShowQueryKey(theaterID, roomID, timeSlotID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof timeSlotsShow>>> = ({ signal }) =>
    timeSlotsShow(theaterID, roomID, timeSlotID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(theaterID) && unref(roomID) && unref(timeSlotID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof timeSlotsShow>>, TError, TData>
}

export type TimeSlotsShowQueryResult = NonNullable<Awaited<ReturnType<typeof timeSlotsShow>>>
export type TimeSlotsShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Show time slot
 */

export function useTimeSlotsShow<
  TData = Awaited<ReturnType<typeof timeSlotsShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  timeSlotID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof timeSlotsShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTimeSlotsShowQueryOptions(theaterID, roomID, timeSlotID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}
