/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiTheaterRequestBody,
  ApiTheaterResponse,
  MiddlewareHttpError,
  TheatersList200,
  TheatersListParams,
} from '.././model'

import { sporedMutator } from '../../spored-mutator'

/**
 * List theaters
 * @summary List theaters
 */
export const theatersList = (params?: MaybeRef<TheatersListParams>, signal?: AbortSignal) => {
  params = unref(params)

  return sporedMutator<TheatersList200>({
    url: `/api/v1/spored/theaters`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getTheatersListQueryKey = (params?: MaybeRef<TheatersListParams>) => {
  return ['api', 'v1', 'spored', 'theaters', ...(params ? [params] : [])] as const
}

export const getTheatersListQueryOptions = <
  TData = Awaited<ReturnType<typeof theatersList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<TheatersListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof theatersList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getTheatersListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof theatersList>>> = ({ signal }) =>
    theatersList(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof theatersList>>,
    TError,
    TData
  >
}

export type TheatersListQueryResult = NonNullable<Awaited<ReturnType<typeof theatersList>>>
export type TheatersListQueryError = MiddlewareHttpError

/**
 * @summary List theaters
 */

export function useTheatersList<
  TData = Awaited<ReturnType<typeof theatersList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<TheatersListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof theatersList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTheatersListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Create theater
 * @summary Create theater
 */
export const theatersCreate = (
  apiTheaterRequestBody: MaybeRef<ApiTheaterRequestBody>,
  signal?: AbortSignal,
) => {
  apiTheaterRequestBody = unref(apiTheaterRequestBody)

  return sporedMutator<ApiTheaterResponse>({
    url: `/api/v1/spored/theaters`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiTheaterRequestBody,
    signal,
  })
}

export const getTheatersCreateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersCreate>>,
    TError,
    { data: ApiTheaterRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof theatersCreate>>,
  TError,
  { data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationKey = ['theatersCreate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof theatersCreate>>,
    { data: ApiTheaterRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return theatersCreate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type TheatersCreateMutationResult = NonNullable<Awaited<ReturnType<typeof theatersCreate>>>
export type TheatersCreateMutationBody = ApiTheaterRequestBody
export type TheatersCreateMutationError = MiddlewareHttpError

/**
 * @summary Create theater
 */
export const useTheatersCreate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof theatersCreate>>,
      TError,
      { data: ApiTheaterRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof theatersCreate>>,
  TError,
  { data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationOptions = getTheatersCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete theater
 * @summary Delete theater
 */
export const theatersDelete = (theaterID: MaybeRef<string>) => {
  theaterID = unref(theaterID)

  return sporedMutator<void>({ url: `/api/v1/spored/theaters/${theaterID}`, method: 'DELETE' })
}

export const getTheatersDeleteMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersDelete>>,
    TError,
    { theaterID: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof theatersDelete>>,
  TError,
  { theaterID: string },
  TContext
> => {
  const mutationKey = ['theatersDelete']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof theatersDelete>>,
    { theaterID: string }
  > = (props) => {
    const { theaterID } = props ?? {}

    return theatersDelete(theaterID)
  }

  return { mutationFn, ...mutationOptions }
}

export type TheatersDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof theatersDelete>>>

export type TheatersDeleteMutationError = MiddlewareHttpError

/**
 * @summary Delete theater
 */
export const useTheatersDelete = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof theatersDelete>>,
      TError,
      { theaterID: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof theatersDelete>>,
  TError,
  { theaterID: string },
  TContext
> => {
  const mutationOptions = getTheatersDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Show theater
 * @summary Show theater
 */
export const theatersShow = (theaterID: MaybeRef<string>, signal?: AbortSignal) => {
  theaterID = unref(theaterID)

  return sporedMutator<ApiTheaterResponse>({
    url: `/api/v1/spored/theaters/${theaterID}`,
    method: 'GET',
    signal,
  })
}

export const getTheatersShowQueryKey = (theaterID?: MaybeRef<string>) => {
  return ['api', 'v1', 'spored', 'theaters', theaterID] as const
}

export const getTheatersShowQueryOptions = <
  TData = Awaited<ReturnType<typeof theatersShow>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof theatersShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getTheatersShowQueryKey(theaterID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof theatersShow>>> = ({ signal }) =>
    theatersShow(theaterID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(theaterID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof theatersShow>>, TError, TData>
}

export type TheatersShowQueryResult = NonNullable<Awaited<ReturnType<typeof theatersShow>>>
export type TheatersShowQueryError = MiddlewareHttpError

/**
 * @summary Show theater
 */

export function useTheatersShow<
  TData = Awaited<ReturnType<typeof theatersShow>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof theatersShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTheatersShowQueryOptions(theaterID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update theater
 * @summary Update theater
 */
export const theatersUpdate = (
  theaterID: MaybeRef<string>,
  apiTheaterRequestBody: MaybeRef<ApiTheaterRequestBody>,
) => {
  theaterID = unref(theaterID)
  apiTheaterRequestBody = unref(apiTheaterRequestBody)

  return sporedMutator<ApiTheaterResponse>({
    url: `/api/v1/spored/theaters/${theaterID}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiTheaterRequestBody,
  })
}

export const getTheatersUpdateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersUpdate>>,
    TError,
    { theaterID: string; data: ApiTheaterRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof theatersUpdate>>,
  TError,
  { theaterID: string; data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationKey = ['theatersUpdate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof theatersUpdate>>,
    { theaterID: string; data: ApiTheaterRequestBody }
  > = (props) => {
    const { theaterID, data } = props ?? {}

    return theatersUpdate(theaterID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type TheatersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof theatersUpdate>>>
export type TheatersUpdateMutationBody = ApiTheaterRequestBody
export type TheatersUpdateMutationError = MiddlewareHttpError

/**
 * @summary Update theater
 */
export const useTheatersUpdate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof theatersUpdate>>,
      TError,
      { theaterID: string; data: ApiTheaterRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof theatersUpdate>>,
  TError,
  { theaterID: string; data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationOptions = getTheatersUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
