/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiTheaterRequestBody,
  ApiTheaterResponse,
  MiddlewareHttpError,
  TheatersList200,
  TheatersListParams,
} from '.././model'

/**
 * List theaters
 * @summary List theaters
 */
export const theatersList = (
  params?: MaybeRef<TheatersListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TheatersList200>> => {
  params = unref(params)

  return axios.default.get(`/theaters`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getTheatersListQueryKey = (params?: MaybeRef<TheatersListParams>) => {
  return ['theaters', ...(params ? [params] : [])] as const
}

export const getTheatersListQueryOptions = <
  TData = Awaited<ReturnType<typeof theatersList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<TheatersListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof theatersList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getTheatersListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof theatersList>>> = ({ signal }) =>
    theatersList(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof theatersList>>,
    TError,
    TData
  >
}

export type TheatersListQueryResult = NonNullable<Awaited<ReturnType<typeof theatersList>>>
export type TheatersListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List theaters
 */

export function useTheatersList<
  TData = Awaited<ReturnType<typeof theatersList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<TheatersListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof theatersList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTheatersListQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Create theater
 * @summary Create theater
 */
export const theatersCreate = (
  apiTheaterRequestBody: MaybeRef<ApiTheaterRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiTheaterResponse>> => {
  apiTheaterRequestBody = unref(apiTheaterRequestBody)

  return axios.default.post(`/theaters`, apiTheaterRequestBody, options)
}

export const getTheatersCreateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersCreate>>,
    TError,
    { data: ApiTheaterRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof theatersCreate>>,
  TError,
  { data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationKey = ['theatersCreate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof theatersCreate>>,
    { data: ApiTheaterRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return theatersCreate(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TheatersCreateMutationResult = NonNullable<Awaited<ReturnType<typeof theatersCreate>>>
export type TheatersCreateMutationBody = ApiTheaterRequestBody
export type TheatersCreateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Create theater
 */
export const useTheatersCreate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersCreate>>,
    TError,
    { data: ApiTheaterRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof theatersCreate>>,
  TError,
  { data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationOptions = getTheatersCreateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete theater
 * @summary Delete theater
 */
export const theatersDelete = (
  theaterID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  theaterID = unref(theaterID)

  return axios.default.delete(`/theaters/${theaterID}`, options)
}

export const getTheatersDeleteMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersDelete>>,
    TError,
    { theaterID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof theatersDelete>>,
  TError,
  { theaterID: string },
  TContext
> => {
  const mutationKey = ['theatersDelete']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof theatersDelete>>,
    { theaterID: string }
  > = (props) => {
    const { theaterID } = props ?? {}

    return theatersDelete(theaterID, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TheatersDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof theatersDelete>>>

export type TheatersDeleteMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Delete theater
 */
export const useTheatersDelete = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersDelete>>,
    TError,
    { theaterID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof theatersDelete>>,
  TError,
  { theaterID: string },
  TContext
> => {
  const mutationOptions = getTheatersDeleteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Show theater
 * @summary Show theater
 */
export const theatersShow = (
  theaterID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiTheaterResponse>> => {
  theaterID = unref(theaterID)

  return axios.default.get(`/theaters/${theaterID}`, options)
}

export const getTheatersShowQueryKey = (theaterID?: MaybeRef<string>) => {
  return ['theaters', theaterID] as const
}

export const getTheatersShowQueryOptions = <
  TData = Awaited<ReturnType<typeof theatersShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof theatersShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getTheatersShowQueryKey(theaterID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof theatersShow>>> = ({ signal }) =>
    theatersShow(theaterID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(theaterID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof theatersShow>>, TError, TData>
}

export type TheatersShowQueryResult = NonNullable<Awaited<ReturnType<typeof theatersShow>>>
export type TheatersShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Show theater
 */

export function useTheatersShow<
  TData = Awaited<ReturnType<typeof theatersShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof theatersShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTheatersShowQueryOptions(theaterID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update theater
 * @summary Update theater
 */
export const theatersUpdate = (
  theaterID: MaybeRef<string>,
  apiTheaterRequestBody: MaybeRef<ApiTheaterRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiTheaterResponse>> => {
  theaterID = unref(theaterID)
  apiTheaterRequestBody = unref(apiTheaterRequestBody)

  return axios.default.put(`/theaters/${theaterID}`, apiTheaterRequestBody, options)
}

export const getTheatersUpdateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersUpdate>>,
    TError,
    { theaterID: string; data: ApiTheaterRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof theatersUpdate>>,
  TError,
  { theaterID: string; data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationKey = ['theatersUpdate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof theatersUpdate>>,
    { theaterID: string; data: ApiTheaterRequestBody }
  > = (props) => {
    const { theaterID, data } = props ?? {}

    return theatersUpdate(theaterID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TheatersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof theatersUpdate>>>
export type TheatersUpdateMutationBody = ApiTheaterRequestBody
export type TheatersUpdateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update theater
 */
export const useTheatersUpdate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof theatersUpdate>>,
    TError,
    { theaterID: string; data: ApiTheaterRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof theatersUpdate>>,
  TError,
  { theaterID: string; data: ApiTheaterRequestBody },
  TContext
> => {
  const mutationOptions = getTheatersUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
