/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiPurchaseRequestBody,
  ApiPurchaseResponse,
  MiddlewareHttpError,
  PurchasesList200,
  PurchasesListParams,
} from '.././model'

/**
 * List purchases
 * @summary List purchases
 */
export const purchasesList = (
  reservationID: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PurchasesList200>> => {
  reservationID = unref(reservationID)
  params = unref(params)

  return axios.default.get(`/reservations/${reservationID}/purchases`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getPurchasesListQueryKey = (
  reservationID?: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
) => {
  return ['reservations', reservationID, 'purchases', ...(params ? [params] : [])] as const
}

export const getPurchasesListQueryOptions = <
  TData = Awaited<ReturnType<typeof purchasesList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  reservationID: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof purchasesList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getPurchasesListQueryKey(reservationID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof purchasesList>>> = ({ signal }) =>
    purchasesList(reservationID, params, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(reservationID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof purchasesList>>, TError, TData>
}

export type PurchasesListQueryResult = NonNullable<Awaited<ReturnType<typeof purchasesList>>>
export type PurchasesListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List purchases
 */

export function usePurchasesList<
  TData = Awaited<ReturnType<typeof purchasesList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  reservationID: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof purchasesList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPurchasesListQueryOptions(reservationID, params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Create purchase
 * @summary Create purchase
 */
export const purchasesCreate = (
  reservationID: MaybeRef<string>,
  apiPurchaseRequestBody: MaybeRef<ApiPurchaseRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiPurchaseResponse>> => {
  reservationID = unref(reservationID)
  apiPurchaseRequestBody = unref(apiPurchaseRequestBody)

  return axios.default.post(
    `/reservations/${reservationID}/purchases`,
    apiPurchaseRequestBody,
    options,
  )
}

export const getPurchasesCreateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesCreate>>,
    TError,
    { reservationID: string; data: ApiPurchaseRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchasesCreate>>,
  TError,
  { reservationID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationKey = ['purchasesCreate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchasesCreate>>,
    { reservationID: string; data: ApiPurchaseRequestBody }
  > = (props) => {
    const { reservationID, data } = props ?? {}

    return purchasesCreate(reservationID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PurchasesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof purchasesCreate>>>
export type PurchasesCreateMutationBody = ApiPurchaseRequestBody
export type PurchasesCreateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Create purchase
 */
export const usePurchasesCreate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesCreate>>,
    TError,
    { reservationID: string; data: ApiPurchaseRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof purchasesCreate>>,
  TError,
  { reservationID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationOptions = getPurchasesCreateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete purchase
 * @summary Delete purchase
 */
export const purchasesDelete = (
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  reservationID = unref(reservationID)
  purchaseID = unref(purchaseID)

  return axios.default.delete(`/reservations/${reservationID}/purchases/${purchaseID}`, options)
}

export const getPurchasesDeleteMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesDelete>>,
    TError,
    { reservationID: string; purchaseID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchasesDelete>>,
  TError,
  { reservationID: string; purchaseID: string },
  TContext
> => {
  const mutationKey = ['purchasesDelete']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchasesDelete>>,
    { reservationID: string; purchaseID: string }
  > = (props) => {
    const { reservationID, purchaseID } = props ?? {}

    return purchasesDelete(reservationID, purchaseID, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PurchasesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof purchasesDelete>>>

export type PurchasesDeleteMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Delete purchase
 */
export const usePurchasesDelete = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesDelete>>,
    TError,
    { reservationID: string; purchaseID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof purchasesDelete>>,
  TError,
  { reservationID: string; purchaseID: string },
  TContext
> => {
  const mutationOptions = getPurchasesDeleteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Show purchase
 * @summary Show purchase
 */
export const purchasesShow = (
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiPurchaseResponse>> => {
  reservationID = unref(reservationID)
  purchaseID = unref(purchaseID)

  return axios.default.get(`/reservations/${reservationID}/purchases/${purchaseID}`, options)
}

export const getPurchasesShowQueryKey = (
  reservationID?: MaybeRef<string>,
  purchaseID?: MaybeRef<string>,
) => {
  return ['reservations', reservationID, 'purchases', purchaseID] as const
}

export const getPurchasesShowQueryOptions = <
  TData = Awaited<ReturnType<typeof purchasesShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof purchasesShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getPurchasesShowQueryKey(reservationID, purchaseID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof purchasesShow>>> = ({ signal }) =>
    purchasesShow(reservationID, purchaseID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(reservationID) && unref(purchaseID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof purchasesShow>>, TError, TData>
}

export type PurchasesShowQueryResult = NonNullable<Awaited<ReturnType<typeof purchasesShow>>>
export type PurchasesShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Show purchase
 */

export function usePurchasesShow<
  TData = Awaited<ReturnType<typeof purchasesShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof purchasesShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPurchasesShowQueryOptions(reservationID, purchaseID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update purchase
 * @summary Update purchase
 */
export const purchasesUpdate = (
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  apiPurchaseRequestBody: MaybeRef<ApiPurchaseRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiPurchaseResponse>> => {
  reservationID = unref(reservationID)
  purchaseID = unref(purchaseID)
  apiPurchaseRequestBody = unref(apiPurchaseRequestBody)

  return axios.default.put(
    `/reservations/${reservationID}/purchases/${purchaseID}`,
    apiPurchaseRequestBody,
    options,
  )
}

export const getPurchasesUpdateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesUpdate>>,
    TError,
    { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchasesUpdate>>,
  TError,
  { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationKey = ['purchasesUpdate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchasesUpdate>>,
    { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody }
  > = (props) => {
    const { reservationID, purchaseID, data } = props ?? {}

    return purchasesUpdate(reservationID, purchaseID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PurchasesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof purchasesUpdate>>>
export type PurchasesUpdateMutationBody = ApiPurchaseRequestBody
export type PurchasesUpdateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update purchase
 */
export const usePurchasesUpdate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesUpdate>>,
    TError,
    { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof purchasesUpdate>>,
  TError,
  { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationOptions = getPurchasesUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
