/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

import { ModelsPurchaseType } from '.././model'
import type { ApiPurchaseResponse, PurchasesList200 } from '.././model'

export const getPurchasesListResponseMock = (): PurchasesList200 => ({
  ...{
    data: faker.helpers.arrayElement([{}, undefined]),
    limit: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    offset: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    total: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
  },
  ...{
    data: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        count: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        created_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        price_per_item_cents: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        type: faker.helpers.arrayElement([
          faker.helpers.arrayElement(Object.values(ModelsPurchaseType)),
          undefined,
        ]),
        updated_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      })),
      undefined,
    ]),
  },
})

export const getPurchasesCreateResponseMock = (
  overrideResponse: Partial<ApiPurchaseResponse> = {},
): ApiPurchaseResponse => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  price_per_item_cents: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  type: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsPurchaseType)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getPurchasesShowResponseMock = (
  overrideResponse: Partial<ApiPurchaseResponse> = {},
): ApiPurchaseResponse => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  price_per_item_cents: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  type: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsPurchaseType)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getPurchasesUpdateResponseMock = (
  overrideResponse: Partial<ApiPurchaseResponse> = {},
): ApiPurchaseResponse => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  price_per_item_cents: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  type: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsPurchaseType)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getPurchasesListMockHandler = (
  overrideResponse?:
    | PurchasesList200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PurchasesList200> | PurchasesList200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/reservations/:reservationID/purchases',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPurchasesListResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getPurchasesCreateMockHandler = (
  overrideResponse?:
    | ApiPurchaseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiPurchaseResponse> | ApiPurchaseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/reservations/:reservationID/purchases',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPurchasesCreateResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getPurchasesDeleteMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/reservations/:reservationID/purchases/:purchaseID',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 204 })
    },
    options,
  )
}

export const getPurchasesShowMockHandler = (
  overrideResponse?:
    | ApiPurchaseResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ApiPurchaseResponse> | ApiPurchaseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/reservations/:reservationID/purchases/:purchaseID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPurchasesShowResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getPurchasesUpdateMockHandler = (
  overrideResponse?:
    | ApiPurchaseResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ApiPurchaseResponse> | ApiPurchaseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/reservations/:reservationID/purchases/:purchaseID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPurchasesUpdateResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getPurchasesMock = () => [
  getPurchasesListMockHandler(),
  getPurchasesCreateMockHandler(),
  getPurchasesDeleteMockHandler(),
  getPurchasesShowMockHandler(),
  getPurchasesUpdateMockHandler(),
]
