/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiPurchaseRequestBody,
  ApiPurchaseResponse,
  MiddlewareHttpError,
  PurchasesList200,
  PurchasesListParams,
} from '.././model'

import { nakupMutator } from '../../nakup-mutator'

/**
 * List purchases
 * @summary List purchases
 */
export const purchasesList = (
  reservationID: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
  signal?: AbortSignal,
) => {
  reservationID = unref(reservationID)
  params = unref(params)

  return nakupMutator<PurchasesList200>({
    url: `/api/v1/nakup/reservations/${reservationID}/purchases`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getPurchasesListQueryKey = (
  reservationID?: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
) => {
  return [
    'api',
    'v1',
    'nakup',
    'reservations',
    reservationID,
    'purchases',
    ...(params ? [params] : []),
  ] as const
}

export const getPurchasesListQueryOptions = <
  TData = Awaited<ReturnType<typeof purchasesList>>,
  TError = MiddlewareHttpError,
>(
  reservationID: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof purchasesList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getPurchasesListQueryKey(reservationID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof purchasesList>>> = ({ signal }) =>
    purchasesList(reservationID, params, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(reservationID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof purchasesList>>, TError, TData>
}

export type PurchasesListQueryResult = NonNullable<Awaited<ReturnType<typeof purchasesList>>>
export type PurchasesListQueryError = MiddlewareHttpError

/**
 * @summary List purchases
 */

export function usePurchasesList<
  TData = Awaited<ReturnType<typeof purchasesList>>,
  TError = MiddlewareHttpError,
>(
  reservationID: MaybeRef<string>,
  params?: MaybeRef<PurchasesListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof purchasesList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPurchasesListQueryOptions(reservationID, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Create purchase
 * @summary Create purchase
 */
export const purchasesCreate = (
  reservationID: MaybeRef<string>,
  apiPurchaseRequestBody: MaybeRef<ApiPurchaseRequestBody>,
  signal?: AbortSignal,
) => {
  reservationID = unref(reservationID)
  apiPurchaseRequestBody = unref(apiPurchaseRequestBody)

  return nakupMutator<ApiPurchaseResponse>({
    url: `/api/v1/nakup/reservations/${reservationID}/purchases`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiPurchaseRequestBody,
    signal,
  })
}

export const getPurchasesCreateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesCreate>>,
    TError,
    { reservationID: string; data: ApiPurchaseRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchasesCreate>>,
  TError,
  { reservationID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationKey = ['purchasesCreate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchasesCreate>>,
    { reservationID: string; data: ApiPurchaseRequestBody }
  > = (props) => {
    const { reservationID, data } = props ?? {}

    return purchasesCreate(reservationID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PurchasesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof purchasesCreate>>>
export type PurchasesCreateMutationBody = ApiPurchaseRequestBody
export type PurchasesCreateMutationError = MiddlewareHttpError

/**
 * @summary Create purchase
 */
export const usePurchasesCreate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purchasesCreate>>,
      TError,
      { reservationID: string; data: ApiPurchaseRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof purchasesCreate>>,
  TError,
  { reservationID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationOptions = getPurchasesCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete purchase
 * @summary Delete purchase
 */
export const purchasesDelete = (reservationID: MaybeRef<string>, purchaseID: MaybeRef<string>) => {
  reservationID = unref(reservationID)
  purchaseID = unref(purchaseID)

  return nakupMutator<void>({
    url: `/api/v1/nakup/reservations/${reservationID}/purchases/${purchaseID}`,
    method: 'DELETE',
  })
}

export const getPurchasesDeleteMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesDelete>>,
    TError,
    { reservationID: string; purchaseID: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchasesDelete>>,
  TError,
  { reservationID: string; purchaseID: string },
  TContext
> => {
  const mutationKey = ['purchasesDelete']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchasesDelete>>,
    { reservationID: string; purchaseID: string }
  > = (props) => {
    const { reservationID, purchaseID } = props ?? {}

    return purchasesDelete(reservationID, purchaseID)
  }

  return { mutationFn, ...mutationOptions }
}

export type PurchasesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof purchasesDelete>>>

export type PurchasesDeleteMutationError = MiddlewareHttpError

/**
 * @summary Delete purchase
 */
export const usePurchasesDelete = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purchasesDelete>>,
      TError,
      { reservationID: string; purchaseID: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof purchasesDelete>>,
  TError,
  { reservationID: string; purchaseID: string },
  TContext
> => {
  const mutationOptions = getPurchasesDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Show purchase
 * @summary Show purchase
 */
export const purchasesShow = (
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  reservationID = unref(reservationID)
  purchaseID = unref(purchaseID)

  return nakupMutator<ApiPurchaseResponse>({
    url: `/api/v1/nakup/reservations/${reservationID}/purchases/${purchaseID}`,
    method: 'GET',
    signal,
  })
}

export const getPurchasesShowQueryKey = (
  reservationID?: MaybeRef<string>,
  purchaseID?: MaybeRef<string>,
) => {
  return ['api', 'v1', 'nakup', 'reservations', reservationID, 'purchases', purchaseID] as const
}

export const getPurchasesShowQueryOptions = <
  TData = Awaited<ReturnType<typeof purchasesShow>>,
  TError = MiddlewareHttpError,
>(
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof purchasesShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getPurchasesShowQueryKey(reservationID, purchaseID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof purchasesShow>>> = ({ signal }) =>
    purchasesShow(reservationID, purchaseID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(reservationID) && unref(purchaseID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof purchasesShow>>, TError, TData>
}

export type PurchasesShowQueryResult = NonNullable<Awaited<ReturnType<typeof purchasesShow>>>
export type PurchasesShowQueryError = MiddlewareHttpError

/**
 * @summary Show purchase
 */

export function usePurchasesShow<
  TData = Awaited<ReturnType<typeof purchasesShow>>,
  TError = MiddlewareHttpError,
>(
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof purchasesShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPurchasesShowQueryOptions(reservationID, purchaseID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update purchase
 * @summary Update purchase
 */
export const purchasesUpdate = (
  reservationID: MaybeRef<string>,
  purchaseID: MaybeRef<string>,
  apiPurchaseRequestBody: MaybeRef<ApiPurchaseRequestBody>,
) => {
  reservationID = unref(reservationID)
  purchaseID = unref(purchaseID)
  apiPurchaseRequestBody = unref(apiPurchaseRequestBody)

  return nakupMutator<ApiPurchaseResponse>({
    url: `/api/v1/nakup/reservations/${reservationID}/purchases/${purchaseID}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiPurchaseRequestBody,
  })
}

export const getPurchasesUpdateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchasesUpdate>>,
    TError,
    { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchasesUpdate>>,
  TError,
  { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationKey = ['purchasesUpdate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchasesUpdate>>,
    { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody }
  > = (props) => {
    const { reservationID, purchaseID, data } = props ?? {}

    return purchasesUpdate(reservationID, purchaseID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PurchasesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof purchasesUpdate>>>
export type PurchasesUpdateMutationBody = ApiPurchaseRequestBody
export type PurchasesUpdateMutationError = MiddlewareHttpError

/**
 * @summary Update purchase
 */
export const usePurchasesUpdate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purchasesUpdate>>,
      TError,
      { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof purchasesUpdate>>,
  TError,
  { reservationID: string; purchaseID: string; data: ApiPurchaseRequestBody },
  TContext
> => {
  const mutationOptions = getPurchasesUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
