/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiReservationRequestBody,
  ApiReservationResponse,
  MiddlewareHttpError,
  MyReservationsList200,
  MyReservationsListParams,
  ReservationsList200,
  ReservationsListParams,
} from '.././model'

/**
 * List reservations
 * @summary List reservations
 */
export const reservationsList = (
  params?: MaybeRef<ReservationsListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ReservationsList200>> => {
  params = unref(params)

  return axios.default.get(`/reservations`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getReservationsListQueryKey = (params?: MaybeRef<ReservationsListParams>) => {
  return ['reservations', ...(params ? [params] : [])] as const
}

export const getReservationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof reservationsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<ReservationsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof reservationsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getReservationsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof reservationsList>>> = ({ signal }) =>
    reservationsList(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof reservationsList>>,
    TError,
    TData
  >
}

export type ReservationsListQueryResult = NonNullable<Awaited<ReturnType<typeof reservationsList>>>
export type ReservationsListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List reservations
 */

export function useReservationsList<
  TData = Awaited<ReturnType<typeof reservationsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<ReservationsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof reservationsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getReservationsListQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Create reservation
 * @summary Create reservation
 */
export const reservationsCreate = (
  apiReservationRequestBody: MaybeRef<ApiReservationRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiReservationResponse>> => {
  apiReservationRequestBody = unref(apiReservationRequestBody)

  return axios.default.post(`/reservations`, apiReservationRequestBody, options)
}

export const getReservationsCreateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsCreate>>,
    TError,
    { data: ApiReservationRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof reservationsCreate>>,
  TError,
  { data: ApiReservationRequestBody },
  TContext
> => {
  const mutationKey = ['reservationsCreate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reservationsCreate>>,
    { data: ApiReservationRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return reservationsCreate(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReservationsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationsCreate>>
>
export type ReservationsCreateMutationBody = ApiReservationRequestBody
export type ReservationsCreateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Create reservation
 */
export const useReservationsCreate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsCreate>>,
    TError,
    { data: ApiReservationRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof reservationsCreate>>,
  TError,
  { data: ApiReservationRequestBody },
  TContext
> => {
  const mutationOptions = getReservationsCreateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete reservation
 * @summary Delete reservation
 */
export const reservationsDelete = (
  reservationID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  reservationID = unref(reservationID)

  return axios.default.delete(`/reservations/${reservationID}`, options)
}

export const getReservationsDeleteMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsDelete>>,
    TError,
    { reservationID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof reservationsDelete>>,
  TError,
  { reservationID: string },
  TContext
> => {
  const mutationKey = ['reservationsDelete']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reservationsDelete>>,
    { reservationID: string }
  > = (props) => {
    const { reservationID } = props ?? {}

    return reservationsDelete(reservationID, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReservationsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationsDelete>>
>

export type ReservationsDeleteMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Delete reservation
 */
export const useReservationsDelete = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsDelete>>,
    TError,
    { reservationID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof reservationsDelete>>,
  TError,
  { reservationID: string },
  TContext
> => {
  const mutationOptions = getReservationsDeleteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Show reservation
 * @summary Show reservation
 */
export const reservationsShow = (
  reservationID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiReservationResponse>> => {
  reservationID = unref(reservationID)

  return axios.default.get(`/reservations/${reservationID}`, options)
}

export const getReservationsShowQueryKey = (reservationID?: MaybeRef<string>) => {
  return ['reservations', reservationID] as const
}

export const getReservationsShowQueryOptions = <
  TData = Awaited<ReturnType<typeof reservationsShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  reservationID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof reservationsShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getReservationsShowQueryKey(reservationID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof reservationsShow>>> = ({ signal }) =>
    reservationsShow(reservationID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(reservationID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof reservationsShow>>, TError, TData>
}

export type ReservationsShowQueryResult = NonNullable<Awaited<ReturnType<typeof reservationsShow>>>
export type ReservationsShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Show reservation
 */

export function useReservationsShow<
  TData = Awaited<ReturnType<typeof reservationsShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  reservationID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof reservationsShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getReservationsShowQueryOptions(reservationID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update reservation
 * @summary Update reservation
 */
export const reservationsUpdate = (
  reservationID: MaybeRef<string>,
  apiReservationRequestBody: MaybeRef<ApiReservationRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiReservationResponse>> => {
  reservationID = unref(reservationID)
  apiReservationRequestBody = unref(apiReservationRequestBody)

  return axios.default.put(`/reservations/${reservationID}`, apiReservationRequestBody, options)
}

export const getReservationsUpdateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsUpdate>>,
    TError,
    { reservationID: string; data: ApiReservationRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof reservationsUpdate>>,
  TError,
  { reservationID: string; data: ApiReservationRequestBody },
  TContext
> => {
  const mutationKey = ['reservationsUpdate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reservationsUpdate>>,
    { reservationID: string; data: ApiReservationRequestBody }
  > = (props) => {
    const { reservationID, data } = props ?? {}

    return reservationsUpdate(reservationID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReservationsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationsUpdate>>
>
export type ReservationsUpdateMutationBody = ApiReservationRequestBody
export type ReservationsUpdateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update reservation
 */
export const useReservationsUpdate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsUpdate>>,
    TError,
    { reservationID: string; data: ApiReservationRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof reservationsUpdate>>,
  TError,
  { reservationID: string; data: ApiReservationRequestBody },
  TContext
> => {
  const mutationOptions = getReservationsUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * List reservations for the currently authenticated user
 * @summary List my reservations
 */
export const myReservationsList = (
  params?: MaybeRef<MyReservationsListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MyReservationsList200>> => {
  params = unref(params)

  return axios.default.get(`/reservations/my`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getMyReservationsListQueryKey = (params?: MaybeRef<MyReservationsListParams>) => {
  return ['reservations', 'my', ...(params ? [params] : [])] as const
}

export const getMyReservationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof myReservationsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<MyReservationsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof myReservationsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getMyReservationsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof myReservationsList>>> = ({ signal }) =>
    myReservationsList(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof myReservationsList>>,
    TError,
    TData
  >
}

export type MyReservationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof myReservationsList>>
>
export type MyReservationsListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List my reservations
 */

export function useMyReservationsList<
  TData = Awaited<ReturnType<typeof myReservationsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<MyReservationsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof myReservationsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMyReservationsListQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}
