/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiReservationRequestBody,
  ApiReservationResponse,
  MiddlewareHttpError,
  MyReservationsList200,
  MyReservationsListParams,
  ReservationsList200,
  ReservationsListParams,
} from '.././model'

import { nakupMutator } from '../../nakup-mutator'

/**
 * List reservations
 * @summary List reservations
 */
export const reservationsList = (
  params?: MaybeRef<ReservationsListParams>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return nakupMutator<ReservationsList200>({
    url: `/api/v1/nakup/reservations`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getReservationsListQueryKey = (params?: MaybeRef<ReservationsListParams>) => {
  return ['api', 'v1', 'nakup', 'reservations', ...(params ? [params] : [])] as const
}

export const getReservationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof reservationsList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<ReservationsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reservationsList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getReservationsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof reservationsList>>> = ({ signal }) =>
    reservationsList(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof reservationsList>>,
    TError,
    TData
  >
}

export type ReservationsListQueryResult = NonNullable<Awaited<ReturnType<typeof reservationsList>>>
export type ReservationsListQueryError = MiddlewareHttpError

/**
 * @summary List reservations
 */

export function useReservationsList<
  TData = Awaited<ReturnType<typeof reservationsList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<ReservationsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reservationsList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getReservationsListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Create reservation
 * @summary Create reservation
 */
export const reservationsCreate = (
  apiReservationRequestBody: MaybeRef<ApiReservationRequestBody>,
  signal?: AbortSignal,
) => {
  apiReservationRequestBody = unref(apiReservationRequestBody)

  return nakupMutator<ApiReservationResponse>({
    url: `/api/v1/nakup/reservations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiReservationRequestBody,
    signal,
  })
}

export const getReservationsCreateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsCreate>>,
    TError,
    { data: ApiReservationRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof reservationsCreate>>,
  TError,
  { data: ApiReservationRequestBody },
  TContext
> => {
  const mutationKey = ['reservationsCreate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reservationsCreate>>,
    { data: ApiReservationRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return reservationsCreate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReservationsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationsCreate>>
>
export type ReservationsCreateMutationBody = ApiReservationRequestBody
export type ReservationsCreateMutationError = MiddlewareHttpError

/**
 * @summary Create reservation
 */
export const useReservationsCreate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reservationsCreate>>,
      TError,
      { data: ApiReservationRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof reservationsCreate>>,
  TError,
  { data: ApiReservationRequestBody },
  TContext
> => {
  const mutationOptions = getReservationsCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete reservation
 * @summary Delete reservation
 */
export const reservationsDelete = (reservationID: MaybeRef<string>) => {
  reservationID = unref(reservationID)

  return nakupMutator<void>({
    url: `/api/v1/nakup/reservations/${reservationID}`,
    method: 'DELETE',
  })
}

export const getReservationsDeleteMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsDelete>>,
    TError,
    { reservationID: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof reservationsDelete>>,
  TError,
  { reservationID: string },
  TContext
> => {
  const mutationKey = ['reservationsDelete']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reservationsDelete>>,
    { reservationID: string }
  > = (props) => {
    const { reservationID } = props ?? {}

    return reservationsDelete(reservationID)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReservationsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationsDelete>>
>

export type ReservationsDeleteMutationError = MiddlewareHttpError

/**
 * @summary Delete reservation
 */
export const useReservationsDelete = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reservationsDelete>>,
      TError,
      { reservationID: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof reservationsDelete>>,
  TError,
  { reservationID: string },
  TContext
> => {
  const mutationOptions = getReservationsDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Show reservation
 * @summary Show reservation
 */
export const reservationsShow = (reservationID: MaybeRef<string>, signal?: AbortSignal) => {
  reservationID = unref(reservationID)

  return nakupMutator<ApiReservationResponse>({
    url: `/api/v1/nakup/reservations/${reservationID}`,
    method: 'GET',
    signal,
  })
}

export const getReservationsShowQueryKey = (reservationID?: MaybeRef<string>) => {
  return ['api', 'v1', 'nakup', 'reservations', reservationID] as const
}

export const getReservationsShowQueryOptions = <
  TData = Awaited<ReturnType<typeof reservationsShow>>,
  TError = MiddlewareHttpError,
>(
  reservationID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reservationsShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getReservationsShowQueryKey(reservationID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof reservationsShow>>> = ({ signal }) =>
    reservationsShow(reservationID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(reservationID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof reservationsShow>>, TError, TData>
}

export type ReservationsShowQueryResult = NonNullable<Awaited<ReturnType<typeof reservationsShow>>>
export type ReservationsShowQueryError = MiddlewareHttpError

/**
 * @summary Show reservation
 */

export function useReservationsShow<
  TData = Awaited<ReturnType<typeof reservationsShow>>,
  TError = MiddlewareHttpError,
>(
  reservationID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof reservationsShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getReservationsShowQueryOptions(reservationID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update reservation
 * @summary Update reservation
 */
export const reservationsUpdate = (
  reservationID: MaybeRef<string>,
  apiReservationRequestBody: MaybeRef<ApiReservationRequestBody>,
) => {
  reservationID = unref(reservationID)
  apiReservationRequestBody = unref(apiReservationRequestBody)

  return nakupMutator<ApiReservationResponse>({
    url: `/api/v1/nakup/reservations/${reservationID}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiReservationRequestBody,
  })
}

export const getReservationsUpdateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reservationsUpdate>>,
    TError,
    { reservationID: string; data: ApiReservationRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof reservationsUpdate>>,
  TError,
  { reservationID: string; data: ApiReservationRequestBody },
  TContext
> => {
  const mutationKey = ['reservationsUpdate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reservationsUpdate>>,
    { reservationID: string; data: ApiReservationRequestBody }
  > = (props) => {
    const { reservationID, data } = props ?? {}

    return reservationsUpdate(reservationID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReservationsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationsUpdate>>
>
export type ReservationsUpdateMutationBody = ApiReservationRequestBody
export type ReservationsUpdateMutationError = MiddlewareHttpError

/**
 * @summary Update reservation
 */
export const useReservationsUpdate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reservationsUpdate>>,
      TError,
      { reservationID: string; data: ApiReservationRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof reservationsUpdate>>,
  TError,
  { reservationID: string; data: ApiReservationRequestBody },
  TContext
> => {
  const mutationOptions = getReservationsUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * List reservations for the currently authenticated user
 * @summary List my reservations
 */
export const myReservationsList = (
  params?: MaybeRef<MyReservationsListParams>,
  signal?: AbortSignal,
) => {
  params = unref(params)

  return nakupMutator<MyReservationsList200>({
    url: `/api/v1/nakup/reservations/my`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getMyReservationsListQueryKey = (params?: MaybeRef<MyReservationsListParams>) => {
  return ['api', 'v1', 'nakup', 'reservations', 'my', ...(params ? [params] : [])] as const
}

export const getMyReservationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof myReservationsList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<MyReservationsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof myReservationsList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getMyReservationsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof myReservationsList>>> = ({ signal }) =>
    myReservationsList(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof myReservationsList>>,
    TError,
    TData
  >
}

export type MyReservationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof myReservationsList>>
>
export type MyReservationsListQueryError = MiddlewareHttpError

/**
 * @summary List my reservations
 */

export function useMyReservationsList<
  TData = Awaited<ReturnType<typeof myReservationsList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<MyReservationsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof myReservationsList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMyReservationsListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
