/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export interface ApiMovieResponse {
  active?: boolean
  created_at?: string
  description?: string
  id?: string
  image_url?: string
  length_minutes?: number
  name?: string
  rating?: number
  updated_at?: string
}
