/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export interface ApiMovieRequest {
  active?: boolean
  /** @minLength 10 */
  description: string
  image_url: string
  /**
   * @minimum 10
   * @maximum 1000
   */
  length_minutes: number
  /**
   * @minimum 0
   * @maximum 10
   */
  rating: number
  /** @minLength 3 */
  title: string
}
