/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export type ApiRoomRequestOperatingMode =
  (typeof ApiRoomRequestOperatingMode)[keyof typeof ApiRoomRequestOperatingMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiRoomRequestOperatingMode = {
  CLOSED: 'CLOSED',
  WEEKDAYS: 'WEEKDAYS',
  WEEKENDS: 'WEEKENDS',
  ALL: 'ALL',
} as const
