/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ApiRoomRequestOperatingMode } from './apiRoomRequestOperatingMode'

export interface ApiRoomRequest {
  /**
   * @minimum 0
   * @maximum 24
   */
  closing_hour: number
  /**
   * @minimum 1
   * @maximum 100
   */
  columns: number
  /** @minLength 3 */
  name: string
  /**
   * @minimum 0
   * @maximum 24
   */
  opening_hour: number
  operating_mode: ApiRoomRequestOperatingMode
  /**
   * @minimum 1
   * @maximum 100
   */
  rows: number
}
