/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ModelsRoomOperatingMode } from './modelsRoomOperatingMode'

export interface ApiRoomResponse {
  closing_hour?: number
  columns?: number
  created_at?: string
  id?: string
  name?: string
  opening_hour?: number
  operating_mode?: ModelsRoomOperatingMode
  rows?: number
  updated_at?: string
}
