/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export interface ApiTimeSlotResponse {
  created_at?: string
  end_time?: string
  id?: string
  movie_id?: string
  room_id?: string
  start_time?: string
  updated_at?: string
}
