/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export type MiddlewareHttpErrorFields = { [key: string]: string }
