/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { MiddlewareHttpErrorFields } from './middlewareHttpErrorFields'

export interface MiddlewareHttpError {
  code?: number
  fields?: MiddlewareHttpErrorFields
  message?: string
}
