/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export type ModelsRoomOperatingMode =
  (typeof ModelsRoomOperatingMode)[keyof typeof ModelsRoomOperatingMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsRoomOperatingMode = {
  Closed: 'CLOSED',
  Weekdays: 'WEEKDAYS',
  Weekends: 'WEEKENDS',
  All: 'ALL',
} as const
