/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { RequestPaginatedResponse } from './requestPaginatedResponse'
import type { MoviesList200AllOf } from './moviesList200AllOf'

export type MoviesList200 = RequestPaginatedResponse & MoviesList200AllOf
