/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { RequestPaginatedResponse } from './requestPaginatedResponse'
import type { TheatersList200AllOf } from './theatersList200AllOf'

export type TheatersList200 = RequestPaginatedResponse & TheatersList200AllOf
