/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { RequestPaginatedResponse } from './requestPaginatedResponse'
import type { TimeSlotsList200AllOf } from './timeSlotsList200AllOf'

export type TimeSlotsList200 = RequestPaginatedResponse & TimeSlotsList200AllOf
