/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { MiddlewareHttpError, ReklameMovieWithTimeslots } from '.././model'

import { reklameMutator } from '../../reklame-mutator'

/**
 * Get a list of movies and their showing times for tomorrow for a specific theater
 * @summary Get advertisements
 */
export const getAdvertisements = (theaterID: MaybeRef<string>, signal?: AbortSignal) => {
  theaterID = unref(theaterID)

  return reklameMutator<ReklameMovieWithTimeslots[]>({
    url: `/api/v1/reklame/advertisements/${theaterID}`,
    method: 'GET',
    signal,
  })
}

export const getGetAdvertisementsQueryKey = (theaterID?: MaybeRef<string>) => {
  return ['api', 'v1', 'reklame', 'advertisements', theaterID] as const
}

export const getGetAdvertisementsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdvertisements>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdvertisements>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getGetAdvertisementsQueryKey(theaterID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdvertisements>>> = ({ signal }) =>
    getAdvertisements(theaterID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(theaterID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAdvertisements>>, TError, TData>
}

export type GetAdvertisementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdvertisements>>
>
export type GetAdvertisementsQueryError = MiddlewareHttpError

/**
 * @summary Get advertisements
 */

export function useGetAdvertisements<
  TData = Awaited<ReturnType<typeof getAdvertisements>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdvertisements>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAdvertisementsQueryOptions(theaterID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
