/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { MiddlewareHttpError, ReklameMovieWithTimeslots } from '.././model'

/**
 * Get a list of movies and their showing times for tomorrow for a specific theater
 * @summary Get advertisements
 */
export const getAdvertisements = (
  theaterID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ReklameMovieWithTimeslots[]>> => {
  theaterID = unref(theaterID)

  return axios.default.get(`/advertisements/${theaterID}`, options)
}

export const getGetAdvertisementsQueryKey = (theaterID?: MaybeRef<string>) => {
  return ['advertisements', theaterID] as const
}

export const getGetAdvertisementsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdvertisements>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAdvertisements>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getGetAdvertisementsQueryKey(theaterID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdvertisements>>> = ({ signal }) =>
    getAdvertisements(theaterID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(theaterID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAdvertisements>>, TError, TData>
}

export type GetAdvertisementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdvertisements>>
>
export type GetAdvertisementsQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Get advertisements
 */

export function useGetAdvertisements<
  TData = Awaited<ReturnType<typeof getAdvertisements>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAdvertisements>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdvertisementsQueryOptions(theaterID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}
