/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

import type { ReklameMovieWithTimeslots } from '.././model'

export const getGetAdvertisementsResponseMock = (): ReklameMovieWithTimeslots[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    movie: faker.helpers.arrayElement([
      {
        active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
        created_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        description: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        image_url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        length_minutes: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        rating: faker.helpers.arrayElement([
          faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
          undefined,
        ]),
        updated_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      },
      undefined,
    ]),
    timeslots: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        created_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        end_time: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        movie_id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        room_id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        start_time: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        updated_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      })),
      undefined,
    ]),
  }))

export const getGetAdvertisementsMockHandler = (
  overrideResponse?:
    | ReklameMovieWithTimeslots[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ReklameMovieWithTimeslots[]> | ReklameMovieWithTimeslots[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/advertisements/:theaterID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetAdvertisementsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getAdvertisementsMock = () => [getGetAdvertisementsMockHandler()]
