/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiMovieRequestBody,
  ApiMovieResponse,
  MiddlewareHttpError,
  MoviesList200,
  MoviesListParams,
} from '.././model'

/**
 * List movies
 * @summary List movies
 */
export const moviesList = (
  params?: MaybeRef<MoviesListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MoviesList200>> => {
  params = unref(params)

  return axios.default.get(`/movies`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getMoviesListQueryKey = (params?: MaybeRef<MoviesListParams>) => {
  return ['movies', ...(params ? [params] : [])] as const
}

export const getMoviesListQueryOptions = <
  TData = Awaited<ReturnType<typeof moviesList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<MoviesListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof moviesList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getMoviesListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof moviesList>>> = ({ signal }) =>
    moviesList(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof moviesList>>,
    TError,
    TData
  >
}

export type MoviesListQueryResult = NonNullable<Awaited<ReturnType<typeof moviesList>>>
export type MoviesListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List movies
 */

export function useMoviesList<
  TData = Awaited<ReturnType<typeof moviesList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<MoviesListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof moviesList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMoviesListQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Create movie
 * @summary Create movie
 */
export const moviesCreate = (
  apiMovieRequestBody: MaybeRef<ApiMovieRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiMovieResponse>> => {
  apiMovieRequestBody = unref(apiMovieRequestBody)

  return axios.default.post(`/movies`, apiMovieRequestBody, options)
}

export const getMoviesCreateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesCreate>>,
    TError,
    { data: ApiMovieRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof moviesCreate>>,
  TError,
  { data: ApiMovieRequestBody },
  TContext
> => {
  const mutationKey = ['moviesCreate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moviesCreate>>,
    { data: ApiMovieRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return moviesCreate(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoviesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof moviesCreate>>>
export type MoviesCreateMutationBody = ApiMovieRequestBody
export type MoviesCreateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Create movie
 */
export const useMoviesCreate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesCreate>>,
    TError,
    { data: ApiMovieRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof moviesCreate>>,
  TError,
  { data: ApiMovieRequestBody },
  TContext
> => {
  const mutationOptions = getMoviesCreateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete movie
 * @summary Delete movie
 */
export const moviesDelete = (
  movieID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  movieID = unref(movieID)

  return axios.default.delete(`/movies/${movieID}`, options)
}

export const getMoviesDeleteMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesDelete>>,
    TError,
    { movieID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof moviesDelete>>,
  TError,
  { movieID: string },
  TContext
> => {
  const mutationKey = ['moviesDelete']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moviesDelete>>,
    { movieID: string }
  > = (props) => {
    const { movieID } = props ?? {}

    return moviesDelete(movieID, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoviesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof moviesDelete>>>

export type MoviesDeleteMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Delete movie
 */
export const useMoviesDelete = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesDelete>>,
    TError,
    { movieID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof moviesDelete>>,
  TError,
  { movieID: string },
  TContext
> => {
  const mutationOptions = getMoviesDeleteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Show movie
 * @summary Show movie
 */
export const moviesShow = (
  movieID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiMovieResponse>> => {
  movieID = unref(movieID)

  return axios.default.get(`/movies/${movieID}`, options)
}

export const getMoviesShowQueryKey = (movieID?: MaybeRef<string>) => {
  return ['movies', movieID] as const
}

export const getMoviesShowQueryOptions = <
  TData = Awaited<ReturnType<typeof moviesShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  movieID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof moviesShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getMoviesShowQueryKey(movieID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof moviesShow>>> = ({ signal }) =>
    moviesShow(movieID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof moviesShow>>, TError, TData>
}

export type MoviesShowQueryResult = NonNullable<Awaited<ReturnType<typeof moviesShow>>>
export type MoviesShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Show movie
 */

export function useMoviesShow<
  TData = Awaited<ReturnType<typeof moviesShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  movieID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof moviesShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMoviesShowQueryOptions(movieID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update movie
 * @summary Update movie
 */
export const moviesUpdate = (
  movieID: MaybeRef<string>,
  apiMovieRequestBody: MaybeRef<ApiMovieRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiMovieResponse>> => {
  movieID = unref(movieID)
  apiMovieRequestBody = unref(apiMovieRequestBody)

  return axios.default.put(`/movies/${movieID}`, apiMovieRequestBody, options)
}

export const getMoviesUpdateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesUpdate>>,
    TError,
    { movieID: string; data: ApiMovieRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof moviesUpdate>>,
  TError,
  { movieID: string; data: ApiMovieRequestBody },
  TContext
> => {
  const mutationKey = ['moviesUpdate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moviesUpdate>>,
    { movieID: string; data: ApiMovieRequestBody }
  > = (props) => {
    const { movieID, data } = props ?? {}

    return moviesUpdate(movieID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoviesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof moviesUpdate>>>
export type MoviesUpdateMutationBody = ApiMovieRequestBody
export type MoviesUpdateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update movie
 */
export const useMoviesUpdate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesUpdate>>,
    TError,
    { movieID: string; data: ApiMovieRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof moviesUpdate>>,
  TError,
  { movieID: string; data: ApiMovieRequestBody },
  TContext
> => {
  const mutationOptions = getMoviesUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
