/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiMovieRequestBody,
  ApiMovieResponse,
  MiddlewareHttpError,
  MoviesList200,
  MoviesListParams,
} from '.././model'

import { sporedMutator } from '../../spored-mutator'

/**
 * List movies
 * @summary List movies
 */
export const moviesList = (params?: MaybeRef<MoviesListParams>, signal?: AbortSignal) => {
  params = unref(params)

  return sporedMutator<MoviesList200>({
    url: `/api/v1/spored/movies`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getMoviesListQueryKey = (params?: MaybeRef<MoviesListParams>) => {
  return ['api', 'v1', 'spored', 'movies', ...(params ? [params] : [])] as const
}

export const getMoviesListQueryOptions = <
  TData = Awaited<ReturnType<typeof moviesList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<MoviesListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getMoviesListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof moviesList>>> = ({ signal }) =>
    moviesList(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof moviesList>>,
    TError,
    TData
  >
}

export type MoviesListQueryResult = NonNullable<Awaited<ReturnType<typeof moviesList>>>
export type MoviesListQueryError = MiddlewareHttpError

/**
 * @summary List movies
 */

export function useMoviesList<
  TData = Awaited<ReturnType<typeof moviesList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<MoviesListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMoviesListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Create movie
 * @summary Create movie
 */
export const moviesCreate = (
  apiMovieRequestBody: MaybeRef<ApiMovieRequestBody>,
  signal?: AbortSignal,
) => {
  apiMovieRequestBody = unref(apiMovieRequestBody)

  return sporedMutator<ApiMovieResponse>({
    url: `/api/v1/spored/movies`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiMovieRequestBody,
    signal,
  })
}

export const getMoviesCreateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesCreate>>,
    TError,
    { data: ApiMovieRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof moviesCreate>>,
  TError,
  { data: ApiMovieRequestBody },
  TContext
> => {
  const mutationKey = ['moviesCreate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moviesCreate>>,
    { data: ApiMovieRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return moviesCreate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoviesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof moviesCreate>>>
export type MoviesCreateMutationBody = ApiMovieRequestBody
export type MoviesCreateMutationError = MiddlewareHttpError

/**
 * @summary Create movie
 */
export const useMoviesCreate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof moviesCreate>>,
      TError,
      { data: ApiMovieRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof moviesCreate>>,
  TError,
  { data: ApiMovieRequestBody },
  TContext
> => {
  const mutationOptions = getMoviesCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete movie
 * @summary Delete movie
 */
export const moviesDelete = (movieID: MaybeRef<string>) => {
  movieID = unref(movieID)

  return sporedMutator<void>({ url: `/api/v1/spored/movies/${movieID}`, method: 'DELETE' })
}

export const getMoviesDeleteMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesDelete>>,
    TError,
    { movieID: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof moviesDelete>>,
  TError,
  { movieID: string },
  TContext
> => {
  const mutationKey = ['moviesDelete']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moviesDelete>>,
    { movieID: string }
  > = (props) => {
    const { movieID } = props ?? {}

    return moviesDelete(movieID)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoviesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof moviesDelete>>>

export type MoviesDeleteMutationError = MiddlewareHttpError

/**
 * @summary Delete movie
 */
export const useMoviesDelete = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof moviesDelete>>,
      TError,
      { movieID: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof moviesDelete>>,
  TError,
  { movieID: string },
  TContext
> => {
  const mutationOptions = getMoviesDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Show movie
 * @summary Show movie
 */
export const moviesShow = (movieID: MaybeRef<string>, signal?: AbortSignal) => {
  movieID = unref(movieID)

  return sporedMutator<ApiMovieResponse>({
    url: `/api/v1/spored/movies/${movieID}`,
    method: 'GET',
    signal,
  })
}

export const getMoviesShowQueryKey = (movieID?: MaybeRef<string>) => {
  return ['api', 'v1', 'spored', 'movies', movieID] as const
}

export const getMoviesShowQueryOptions = <
  TData = Awaited<ReturnType<typeof moviesShow>>,
  TError = MiddlewareHttpError,
>(
  movieID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getMoviesShowQueryKey(movieID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof moviesShow>>> = ({ signal }) =>
    moviesShow(movieID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof moviesShow>>, TError, TData>
}

export type MoviesShowQueryResult = NonNullable<Awaited<ReturnType<typeof moviesShow>>>
export type MoviesShowQueryError = MiddlewareHttpError

/**
 * @summary Show movie
 */

export function useMoviesShow<
  TData = Awaited<ReturnType<typeof moviesShow>>,
  TError = MiddlewareHttpError,
>(
  movieID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof moviesShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMoviesShowQueryOptions(movieID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update movie
 * @summary Update movie
 */
export const moviesUpdate = (
  movieID: MaybeRef<string>,
  apiMovieRequestBody: MaybeRef<ApiMovieRequestBody>,
) => {
  movieID = unref(movieID)
  apiMovieRequestBody = unref(apiMovieRequestBody)

  return sporedMutator<ApiMovieResponse>({
    url: `/api/v1/spored/movies/${movieID}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiMovieRequestBody,
  })
}

export const getMoviesUpdateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moviesUpdate>>,
    TError,
    { movieID: string; data: ApiMovieRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof moviesUpdate>>,
  TError,
  { movieID: string; data: ApiMovieRequestBody },
  TContext
> => {
  const mutationKey = ['moviesUpdate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moviesUpdate>>,
    { movieID: string; data: ApiMovieRequestBody }
  > = (props) => {
    const { movieID, data } = props ?? {}

    return moviesUpdate(movieID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoviesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof moviesUpdate>>>
export type MoviesUpdateMutationBody = ApiMovieRequestBody
export type MoviesUpdateMutationError = MiddlewareHttpError

/**
 * @summary Update movie
 */
export const useMoviesUpdate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof moviesUpdate>>,
      TError,
      { movieID: string; data: ApiMovieRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof moviesUpdate>>,
  TError,
  { movieID: string; data: ApiMovieRequestBody },
  TContext
> => {
  const mutationOptions = getMoviesUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
