/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiRoomRequestBody,
  ApiRoomResponse,
  MiddlewareHttpError,
  RoomsList200,
  RoomsListParams,
} from '.././model'

/**
 * List rooms
 * @summary List rooms
 */
export const roomsList = (
  theaterID: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RoomsList200>> => {
  theaterID = unref(theaterID)
  params = unref(params)

  return axios.default.get(`/theaters/${theaterID}/rooms`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getRoomsListQueryKey = (
  theaterID?: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
) => {
  return ['theaters', theaterID, 'rooms', ...(params ? [params] : [])] as const
}

export const getRoomsListQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof roomsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getRoomsListQueryKey(theaterID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsList>>> = ({ signal }) =>
    roomsList(theaterID, params, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(theaterID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof roomsList>>, TError, TData>
}

export type RoomsListQueryResult = NonNullable<Awaited<ReturnType<typeof roomsList>>>
export type RoomsListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List rooms
 */

export function useRoomsList<
  TData = Awaited<ReturnType<typeof roomsList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof roomsList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRoomsListQueryOptions(theaterID, params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Create room
 * @summary Create room
 */
export const roomsCreate = (
  theaterID: MaybeRef<string>,
  apiRoomRequestBody: MaybeRef<ApiRoomRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiRoomResponse>> => {
  theaterID = unref(theaterID)
  apiRoomRequestBody = unref(apiRoomRequestBody)

  return axios.default.post(`/theaters/${theaterID}/rooms`, apiRoomRequestBody, options)
}

export const getRoomsCreateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsCreate>>,
    TError,
    { theaterID: string; data: ApiRoomRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsCreate>>,
  TError,
  { theaterID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationKey = ['roomsCreate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsCreate>>,
    { theaterID: string; data: ApiRoomRequestBody }
  > = (props) => {
    const { theaterID, data } = props ?? {}

    return roomsCreate(theaterID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RoomsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof roomsCreate>>>
export type RoomsCreateMutationBody = ApiRoomRequestBody
export type RoomsCreateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Create room
 */
export const useRoomsCreate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsCreate>>,
    TError,
    { theaterID: string; data: ApiRoomRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof roomsCreate>>,
  TError,
  { theaterID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationOptions = getRoomsCreateMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete room
 * @summary Delete room
 */
export const roomsDelete = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)

  return axios.default.delete(`/theaters/${theaterID}/rooms/${roomID}`, options)
}

export const getRoomsDeleteMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsDelete>>,
    TError,
    { theaterID: string; roomID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsDelete>>,
  TError,
  { theaterID: string; roomID: string },
  TContext
> => {
  const mutationKey = ['roomsDelete']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsDelete>>,
    { theaterID: string; roomID: string }
  > = (props) => {
    const { theaterID, roomID } = props ?? {}

    return roomsDelete(theaterID, roomID, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RoomsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof roomsDelete>>>

export type RoomsDeleteMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Delete room
 */
export const useRoomsDelete = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsDelete>>,
    TError,
    { theaterID: string; roomID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof roomsDelete>>,
  TError,
  { theaterID: string; roomID: string },
  TContext
> => {
  const mutationOptions = getRoomsDeleteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Show room
 * @summary Show room
 */
export const roomsShow = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiRoomResponse>> => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)

  return axios.default.get(`/theaters/${theaterID}/rooms/${roomID}`, options)
}

export const getRoomsShowQueryKey = (theaterID?: MaybeRef<string>, roomID?: MaybeRef<string>) => {
  return ['theaters', theaterID, 'rooms', roomID] as const
}

export const getRoomsShowQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof roomsShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getRoomsShowQueryKey(theaterID, roomID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsShow>>> = ({ signal }) =>
    roomsShow(theaterID, roomID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(theaterID) && unref(roomID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof roomsShow>>, TError, TData>
}

export type RoomsShowQueryResult = NonNullable<Awaited<ReturnType<typeof roomsShow>>>
export type RoomsShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Show room
 */

export function useRoomsShow<
  TData = Awaited<ReturnType<typeof roomsShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof roomsShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRoomsShowQueryOptions(theaterID, roomID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update room
 * @summary Update room
 */
export const roomsUpdate = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  apiRoomRequestBody: MaybeRef<ApiRoomRequestBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiRoomResponse>> => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)
  apiRoomRequestBody = unref(apiRoomRequestBody)

  return axios.default.put(`/theaters/${theaterID}/rooms/${roomID}`, apiRoomRequestBody, options)
}

export const getRoomsUpdateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsUpdate>>,
    TError,
    { theaterID: string; roomID: string; data: ApiRoomRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsUpdate>>,
  TError,
  { theaterID: string; roomID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationKey = ['roomsUpdate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsUpdate>>,
    { theaterID: string; roomID: string; data: ApiRoomRequestBody }
  > = (props) => {
    const { theaterID, roomID, data } = props ?? {}

    return roomsUpdate(theaterID, roomID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RoomsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof roomsUpdate>>>
export type RoomsUpdateMutationBody = ApiRoomRequestBody
export type RoomsUpdateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update room
 */
export const useRoomsUpdate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsUpdate>>,
    TError,
    { theaterID: string; roomID: string; data: ApiRoomRequestBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof roomsUpdate>>,
  TError,
  { theaterID: string; roomID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationOptions = getRoomsUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
