/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

import { ModelsRoomOperatingMode } from '.././model'
import type { ApiRoomResponse, RoomsList200 } from '.././model'

export const getRoomsListResponseMock = (): RoomsList200 => ({
  ...{
    data: faker.helpers.arrayElement([{}, undefined]),
    limit: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    offset: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    total: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
  },
  ...{
    data: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        closing_hour: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        columns: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        created_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        opening_hour: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        operating_mode: faker.helpers.arrayElement([
          faker.helpers.arrayElement(Object.values(ModelsRoomOperatingMode)),
          undefined,
        ]),
        rows: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined,
        ]),
        updated_at: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
      })),
      undefined,
    ]),
  },
})

export const getRoomsCreateResponseMock = (
  overrideResponse: Partial<ApiRoomResponse> = {},
): ApiRoomResponse => ({
  closing_hour: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  columns: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  opening_hour: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  operating_mode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsRoomOperatingMode)),
    undefined,
  ]),
  rows: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getRoomsShowResponseMock = (
  overrideResponse: Partial<ApiRoomResponse> = {},
): ApiRoomResponse => ({
  closing_hour: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  columns: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  opening_hour: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  operating_mode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsRoomOperatingMode)),
    undefined,
  ]),
  rows: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getRoomsUpdateResponseMock = (
  overrideResponse: Partial<ApiRoomResponse> = {},
): ApiRoomResponse => ({
  closing_hour: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  columns: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  opening_hour: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  operating_mode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsRoomOperatingMode)),
    undefined,
  ]),
  rows: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getRoomsListMockHandler = (
  overrideResponse?:
    | RoomsList200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<RoomsList200> | RoomsList200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/theaters/:theaterID/rooms',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRoomsListResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getRoomsCreateMockHandler = (
  overrideResponse?:
    | ApiRoomResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiRoomResponse> | ApiRoomResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/theaters/:theaterID/rooms',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRoomsCreateResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getRoomsDeleteMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/theaters/:theaterID/rooms/:roomID',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 204 })
    },
    options,
  )
}

export const getRoomsShowMockHandler = (
  overrideResponse?:
    | ApiRoomResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ApiRoomResponse> | ApiRoomResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/theaters/:theaterID/rooms/:roomID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRoomsShowResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getRoomsUpdateMockHandler = (
  overrideResponse?:
    | ApiRoomResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ApiRoomResponse> | ApiRoomResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/theaters/:theaterID/rooms/:roomID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRoomsUpdateResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getRoomsMock = () => [
  getRoomsListMockHandler(),
  getRoomsCreateMockHandler(),
  getRoomsDeleteMockHandler(),
  getRoomsShowMockHandler(),
  getRoomsUpdateMockHandler(),
]
