/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiRoomRequestBody,
  ApiRoomResponse,
  MiddlewareHttpError,
  RoomsList200,
  RoomsListParams,
} from '.././model'

import { sporedMutator } from '../../spored-mutator'

/**
 * List rooms
 * @summary List rooms
 */
export const roomsList = (
  theaterID: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
  signal?: AbortSignal,
) => {
  theaterID = unref(theaterID)
  params = unref(params)

  return sporedMutator<RoomsList200>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getRoomsListQueryKey = (
  theaterID?: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
) => {
  return [
    'api',
    'v1',
    'spored',
    'theaters',
    theaterID,
    'rooms',
    ...(params ? [params] : []),
  ] as const
}

export const getRoomsListQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsList>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getRoomsListQueryKey(theaterID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsList>>> = ({ signal }) =>
    roomsList(theaterID, params, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(theaterID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof roomsList>>, TError, TData>
}

export type RoomsListQueryResult = NonNullable<Awaited<ReturnType<typeof roomsList>>>
export type RoomsListQueryError = MiddlewareHttpError

/**
 * @summary List rooms
 */

export function useRoomsList<
  TData = Awaited<ReturnType<typeof roomsList>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  params?: MaybeRef<RoomsListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsListQueryOptions(theaterID, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Create room
 * @summary Create room
 */
export const roomsCreate = (
  theaterID: MaybeRef<string>,
  apiRoomRequestBody: MaybeRef<ApiRoomRequestBody>,
  signal?: AbortSignal,
) => {
  theaterID = unref(theaterID)
  apiRoomRequestBody = unref(apiRoomRequestBody)

  return sporedMutator<ApiRoomResponse>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiRoomRequestBody,
    signal,
  })
}

export const getRoomsCreateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsCreate>>,
    TError,
    { theaterID: string; data: ApiRoomRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsCreate>>,
  TError,
  { theaterID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationKey = ['roomsCreate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsCreate>>,
    { theaterID: string; data: ApiRoomRequestBody }
  > = (props) => {
    const { theaterID, data } = props ?? {}

    return roomsCreate(theaterID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type RoomsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof roomsCreate>>>
export type RoomsCreateMutationBody = ApiRoomRequestBody
export type RoomsCreateMutationError = MiddlewareHttpError

/**
 * @summary Create room
 */
export const useRoomsCreate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsCreate>>,
      TError,
      { theaterID: string; data: ApiRoomRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof roomsCreate>>,
  TError,
  { theaterID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationOptions = getRoomsCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete room
 * @summary Delete room
 */
export const roomsDelete = (theaterID: MaybeRef<string>, roomID: MaybeRef<string>) => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)

  return sporedMutator<void>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms/${roomID}`,
    method: 'DELETE',
  })
}

export const getRoomsDeleteMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsDelete>>,
    TError,
    { theaterID: string; roomID: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsDelete>>,
  TError,
  { theaterID: string; roomID: string },
  TContext
> => {
  const mutationKey = ['roomsDelete']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsDelete>>,
    { theaterID: string; roomID: string }
  > = (props) => {
    const { theaterID, roomID } = props ?? {}

    return roomsDelete(theaterID, roomID)
  }

  return { mutationFn, ...mutationOptions }
}

export type RoomsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof roomsDelete>>>

export type RoomsDeleteMutationError = MiddlewareHttpError

/**
 * @summary Delete room
 */
export const useRoomsDelete = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsDelete>>,
      TError,
      { theaterID: string; roomID: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof roomsDelete>>,
  TError,
  { theaterID: string; roomID: string },
  TContext
> => {
  const mutationOptions = getRoomsDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Show room
 * @summary Show room
 */
export const roomsShow = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)

  return sporedMutator<ApiRoomResponse>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms/${roomID}`,
    method: 'GET',
    signal,
  })
}

export const getRoomsShowQueryKey = (theaterID?: MaybeRef<string>, roomID?: MaybeRef<string>) => {
  return ['api', 'v1', 'spored', 'theaters', theaterID, 'rooms', roomID] as const
}

export const getRoomsShowQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsShow>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getRoomsShowQueryKey(theaterID, roomID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsShow>>> = ({ signal }) =>
    roomsShow(theaterID, roomID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(theaterID) && unref(roomID))),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof roomsShow>>, TError, TData>
}

export type RoomsShowQueryResult = NonNullable<Awaited<ReturnType<typeof roomsShow>>>
export type RoomsShowQueryError = MiddlewareHttpError

/**
 * @summary Show room
 */

export function useRoomsShow<
  TData = Awaited<ReturnType<typeof roomsShow>>,
  TError = MiddlewareHttpError,
>(
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsShowQueryOptions(theaterID, roomID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update room
 * @summary Update room
 */
export const roomsUpdate = (
  theaterID: MaybeRef<string>,
  roomID: MaybeRef<string>,
  apiRoomRequestBody: MaybeRef<ApiRoomRequestBody>,
) => {
  theaterID = unref(theaterID)
  roomID = unref(roomID)
  apiRoomRequestBody = unref(apiRoomRequestBody)

  return sporedMutator<ApiRoomResponse>({
    url: `/api/v1/spored/theaters/${theaterID}/rooms/${roomID}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiRoomRequestBody,
  })
}

export const getRoomsUpdateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsUpdate>>,
    TError,
    { theaterID: string; roomID: string; data: ApiRoomRequestBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsUpdate>>,
  TError,
  { theaterID: string; roomID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationKey = ['roomsUpdate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsUpdate>>,
    { theaterID: string; roomID: string; data: ApiRoomRequestBody }
  > = (props) => {
    const { theaterID, roomID, data } = props ?? {}

    return roomsUpdate(theaterID, roomID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type RoomsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof roomsUpdate>>>
export type RoomsUpdateMutationBody = ApiRoomRequestBody
export type RoomsUpdateMutationError = MiddlewareHttpError

/**
 * @summary Update room
 */
export const useRoomsUpdate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsUpdate>>,
      TError,
      { theaterID: string; roomID: string; data: ApiRoomRequestBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof roomsUpdate>>,
  TError,
  { theaterID: string; roomID: string; data: ApiRoomRequestBody },
  TContext
> => {
  const mutationOptions = getRoomsUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
