/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export * from './middlewareHttpError'
export * from './middlewareHttpErrorFields'
export * from './modelsAPIMovieResponse'
export * from './modelsAPITimeSlotResponse'
export * from './reklameMovieWithTimeslots'
