/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export interface ModelsAPITimeSlotResponse {
  /** created at */
  created_at?: string
  /** end time */
  end_time?: string
  /** id */
  id?: string
  /** movie id */
  movie_id?: string
  /** room id */
  room_id?: string
  /** start time */
  start_time?: string
  /** updated at */
  updated_at?: string
}
