/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */

export interface ModelsAPIMovieResponse {
  /** active */
  active?: boolean
  /** created at */
  created_at?: string
  /** description */
  description?: string
  /** id */
  id?: string
  /** image url */
  image_url?: string
  /** length minutes */
  length_minutes?: number
  /** name */
  name?: string
  /** rating */
  rating?: number
  /** updated at */
  updated_at?: string
}
