/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Reklame API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type { ModelsAPIMovieResponse } from './modelsAPIMovieResponse'
import type { ModelsAPITimeSlotResponse } from './modelsAPITimeSlotResponse'

export interface ReklameMovieWithTimeslots {
  movie?: ModelsAPIMovieResponse
  timeslots?: ModelsAPITimeSlotResponse[]
}
