/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiAdminCreateUserRequest,
  ApiAdminUpdateUserRequest,
  ApiUserResponse,
  MiddlewareHttpError,
  UsersListParams,
} from '.././model'

/**
 * List all users (admin endpoint)
 * @summary List users
 */
export const usersList = (
  params?: MaybeRef<UsersListParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse[]>> => {
  params = unref(params)

  return axios.default.get(`/users`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  })
}

export const getUsersListQueryKey = (params?: MaybeRef<UsersListParams>) => {
  return ['users', ...(params ? [params] : [])] as const
}

export const getUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof usersList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<UsersListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof usersList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getUsersListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersList>>> = ({ signal }) =>
    usersList(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersList>>,
    TError,
    TData
  >
}

export type UsersListQueryResult = NonNullable<Awaited<ReturnType<typeof usersList>>>
export type UsersListQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary List users
 */

export function useUsersList<
  TData = Awaited<ReturnType<typeof usersList>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  params?: MaybeRef<UsersListParams>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof usersList>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersListQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Create a new user with any role (admin only)
 * @summary Create user (admin)
 */
export const adminCreateUser = (
  apiAdminCreateUserRequest: MaybeRef<ApiAdminCreateUserRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  apiAdminCreateUserRequest = unref(apiAdminCreateUserRequest)

  return axios.default.post(`/users`, apiAdminCreateUserRequest, options)
}

export const getAdminCreateUserMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminCreateUser>>,
    TError,
    { data: ApiAdminCreateUserRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminCreateUser>>,
  TError,
  { data: ApiAdminCreateUserRequest },
  TContext
> => {
  const mutationKey = ['adminCreateUser']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminCreateUser>>,
    { data: ApiAdminCreateUserRequest }
  > = (props) => {
    const { data } = props ?? {}

    return adminCreateUser(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateUser>>>
export type AdminCreateUserMutationBody = ApiAdminCreateUserRequest
export type AdminCreateUserMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Create user (admin)
 */
export const useAdminCreateUser = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminCreateUser>>,
    TError,
    { data: ApiAdminCreateUserRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof adminCreateUser>>,
  TError,
  { data: ApiAdminCreateUserRequest },
  TContext
> => {
  const mutationOptions = getAdminCreateUserMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete a specific user (admin endpoint)
 * @summary Delete user
 */
export const usersDelete = (
  userID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  userID = unref(userID)

  return axios.default.delete(`/users/${userID}`, options)
}

export const getUsersDeleteMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersDelete>>,
    TError,
    { userID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersDelete>>,
  TError,
  { userID: string },
  TContext
> => {
  const mutationKey = ['usersDelete']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersDelete>>,
    { userID: string }
  > = (props) => {
    const { userID } = props ?? {}

    return usersDelete(userID, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof usersDelete>>>

export type UsersDeleteMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Delete user
 */
export const useUsersDelete = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersDelete>>,
    TError,
    { userID: string },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof usersDelete>>,
  TError,
  { userID: string },
  TContext
> => {
  const mutationOptions = getUsersDeleteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Get a specific user by ID (admin endpoint)
 * @summary Get user by ID
 */
export const usersShow = (
  userID: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  userID = unref(userID)

  return axios.default.get(`/users/${userID}`, options)
}

export const getUsersShowQueryKey = (userID?: MaybeRef<string>) => {
  return ['users', userID] as const
}

export const getUsersShowQueryOptions = <
  TData = Awaited<ReturnType<typeof usersShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  userID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = getUsersShowQueryKey(userID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersShow>>> = ({ signal }) =>
    usersShow(userID, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(userID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>
}

export type UsersShowQueryResult = NonNullable<Awaited<ReturnType<typeof usersShow>>>
export type UsersShowQueryError = AxiosError<MiddlewareHttpError>

/**
 * @summary Get user by ID
 */

export function useUsersShow<
  TData = Awaited<ReturnType<typeof usersShow>>,
  TError = AxiosError<MiddlewareHttpError>,
>(
  userID: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>
    axios?: AxiosRequestConfig
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersShowQueryOptions(userID, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

/**
 * Update a specific user (admin endpoint)
 * @summary Update user
 */
export const usersUpdate = (
  userID: MaybeRef<string>,
  apiAdminUpdateUserRequest: MaybeRef<ApiAdminUpdateUserRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiUserResponse>> => {
  userID = unref(userID)
  apiAdminUpdateUserRequest = unref(apiAdminUpdateUserRequest)

  return axios.default.put(`/users/${userID}`, apiAdminUpdateUserRequest, options)
}

export const getUsersUpdateMutationOptions = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersUpdate>>,
    TError,
    { userID: string; data: ApiAdminUpdateUserRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersUpdate>>,
  TError,
  { userID: string; data: ApiAdminUpdateUserRequest },
  TContext
> => {
  const mutationKey = ['usersUpdate']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersUpdate>>,
    { userID: string; data: ApiAdminUpdateUserRequest }
  > = (props) => {
    const { userID, data } = props ?? {}

    return usersUpdate(userID, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof usersUpdate>>>
export type UsersUpdateMutationBody = ApiAdminUpdateUserRequest
export type UsersUpdateMutationError = AxiosError<MiddlewareHttpError>

/**
 * @summary Update user
 */
export const useUsersUpdate = <
  TError = AxiosError<MiddlewareHttpError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersUpdate>>,
    TError,
    { userID: string; data: ApiAdminUpdateUserRequest },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationReturnType<
  Awaited<ReturnType<typeof usersUpdate>>,
  TError,
  { userID: string; data: ApiAdminUpdateUserRequest },
  TContext
> => {
  const mutationOptions = getUsersUpdateMutationOptions(options)

  return useMutation(mutationOptions)
}
