/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type {
  ApiAdminCreateUserRequest,
  ApiAdminUpdateUserRequest,
  ApiUserResponse,
  MiddlewareHttpError,
  UsersListParams,
} from '.././model'

import { authMutator } from '../../auth-mutator'

/**
 * List all users (admin endpoint)
 * @summary List users
 */
export const usersList = (params?: MaybeRef<UsersListParams>, signal?: AbortSignal) => {
  params = unref(params)

  return authMutator<ApiUserResponse[]>({
    url: `/api/v1/auth/users`,
    method: 'GET',
    params: unref(params),
    signal,
  })
}

export const getUsersListQueryKey = (params?: MaybeRef<UsersListParams>) => {
  return ['api', 'v1', 'auth', 'users', ...(params ? [params] : [])] as const
}

export const getUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof usersList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<UsersListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersList>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getUsersListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersList>>> = ({ signal }) =>
    usersList(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersList>>,
    TError,
    TData
  >
}

export type UsersListQueryResult = NonNullable<Awaited<ReturnType<typeof usersList>>>
export type UsersListQueryError = MiddlewareHttpError

/**
 * @summary List users
 */

export function useUsersList<
  TData = Awaited<ReturnType<typeof usersList>>,
  TError = MiddlewareHttpError,
>(
  params?: MaybeRef<UsersListParams>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersList>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUsersListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Create a new user with any role (admin only)
 * @summary Create user (admin)
 */
export const adminCreateUser = (
  apiAdminCreateUserRequest: MaybeRef<ApiAdminCreateUserRequest>,
  signal?: AbortSignal,
) => {
  apiAdminCreateUserRequest = unref(apiAdminCreateUserRequest)

  return authMutator<ApiUserResponse>({
    url: `/api/v1/auth/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: apiAdminCreateUserRequest,
    signal,
  })
}

export const getAdminCreateUserMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminCreateUser>>,
    TError,
    { data: ApiAdminCreateUserRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminCreateUser>>,
  TError,
  { data: ApiAdminCreateUserRequest },
  TContext
> => {
  const mutationKey = ['adminCreateUser']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminCreateUser>>,
    { data: ApiAdminCreateUserRequest }
  > = (props) => {
    const { data } = props ?? {}

    return adminCreateUser(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateUser>>>
export type AdminCreateUserMutationBody = ApiAdminCreateUserRequest
export type AdminCreateUserMutationError = MiddlewareHttpError

/**
 * @summary Create user (admin)
 */
export const useAdminCreateUser = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminCreateUser>>,
      TError,
      { data: ApiAdminCreateUserRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminCreateUser>>,
  TError,
  { data: ApiAdminCreateUserRequest },
  TContext
> => {
  const mutationOptions = getAdminCreateUserMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete a specific user (admin endpoint)
 * @summary Delete user
 */
export const usersDelete = (userID: MaybeRef<string>) => {
  userID = unref(userID)

  return authMutator<void>({ url: `/api/v1/auth/users/${userID}`, method: 'DELETE' })
}

export const getUsersDeleteMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersDelete>>,
    TError,
    { userID: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersDelete>>,
  TError,
  { userID: string },
  TContext
> => {
  const mutationKey = ['usersDelete']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersDelete>>,
    { userID: string }
  > = (props) => {
    const { userID } = props ?? {}

    return usersDelete(userID)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof usersDelete>>>

export type UsersDeleteMutationError = MiddlewareHttpError

/**
 * @summary Delete user
 */
export const useUsersDelete = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersDelete>>,
      TError,
      { userID: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof usersDelete>>,
  TError,
  { userID: string },
  TContext
> => {
  const mutationOptions = getUsersDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get a specific user by ID (admin endpoint)
 * @summary Get user by ID
 */
export const usersShow = (userID: MaybeRef<string>, signal?: AbortSignal) => {
  userID = unref(userID)

  return authMutator<ApiUserResponse>({
    url: `/api/v1/auth/users/${userID}`,
    method: 'GET',
    signal,
  })
}

export const getUsersShowQueryKey = (userID?: MaybeRef<string>) => {
  return ['api', 'v1', 'auth', 'users', userID] as const
}

export const getUsersShowQueryOptions = <
  TData = Awaited<ReturnType<typeof usersShow>>,
  TError = MiddlewareHttpError,
>(
  userID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = getUsersShowQueryKey(userID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersShow>>> = ({ signal }) =>
    usersShow(userID, signal)

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(userID)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>
}

export type UsersShowQueryResult = NonNullable<Awaited<ReturnType<typeof usersShow>>>
export type UsersShowQueryError = MiddlewareHttpError

/**
 * @summary Get user by ID
 */

export function useUsersShow<
  TData = Awaited<ReturnType<typeof usersShow>>,
  TError = MiddlewareHttpError,
>(
  userID: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUsersShowQueryOptions(userID, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * Update a specific user (admin endpoint)
 * @summary Update user
 */
export const usersUpdate = (
  userID: MaybeRef<string>,
  apiAdminUpdateUserRequest: MaybeRef<ApiAdminUpdateUserRequest>,
) => {
  userID = unref(userID)
  apiAdminUpdateUserRequest = unref(apiAdminUpdateUserRequest)

  return authMutator<ApiUserResponse>({
    url: `/api/v1/auth/users/${userID}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: apiAdminUpdateUserRequest,
  })
}

export const getUsersUpdateMutationOptions = <
  TError = MiddlewareHttpError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersUpdate>>,
    TError,
    { userID: string; data: ApiAdminUpdateUserRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersUpdate>>,
  TError,
  { userID: string; data: ApiAdminUpdateUserRequest },
  TContext
> => {
  const mutationKey = ['usersUpdate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersUpdate>>,
    { userID: string; data: ApiAdminUpdateUserRequest }
  > = (props) => {
    const { userID, data } = props ?? {}

    return usersUpdate(userID, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof usersUpdate>>>
export type UsersUpdateMutationBody = ApiAdminUpdateUserRequest
export type UsersUpdateMutationError = MiddlewareHttpError

/**
 * @summary Update user
 */
export const useUsersUpdate = <TError = MiddlewareHttpError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersUpdate>>,
      TError,
      { userID: string; data: ApiAdminUpdateUserRequest },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof usersUpdate>>,
  TError,
  { userID: string; data: ApiAdminUpdateUserRequest },
  TContext
> => {
  const mutationOptions = getUsersUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
