/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, delay, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

import { ModelsUserRole } from '.././model'
import type { ApiUserResponse } from '.././model'

export const getUsersListResponseMock = (): ApiUserResponse[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    created_at: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    email: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    first_name: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    id: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    last_name: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    role: faker.helpers.arrayElement([
      faker.helpers.arrayElement(Object.values(ModelsUserRole)),
      undefined,
    ]),
    updated_at: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  }))

export const getAdminCreateUserResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getUsersShowResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getUsersUpdateResponseMock = (
  overrideResponse: Partial<ApiUserResponse> = {},
): ApiUserResponse => ({
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  created_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  first_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  last_name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  role: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ModelsUserRole)),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
})

export const getUsersListMockHandler = (
  overrideResponse?:
    | ApiUserResponse[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ApiUserResponse[]> | ApiUserResponse[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/users',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUsersListResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getAdminCreateUserMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/users',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminCreateUserResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getUsersDeleteMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/users/:userID',
    async (info) => {
      await delay(1000)
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info)
      }
      return new HttpResponse(null, { status: 204 })
    },
    options,
  )
}

export const getUsersShowMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/users/:userID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUsersShowResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getUsersUpdateMockHandler = (
  overrideResponse?:
    | ApiUserResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ApiUserResponse> | ApiUserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/users/:userID',
    async (info) => {
      await delay(1000)

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUsersUpdateResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getUsersMock = () => [
  getUsersListMockHandler(),
  getAdminCreateUserMockHandler(),
  getUsersDeleteMockHandler(),
  getUsersShowMockHandler(),
  getUsersUpdateMockHandler(),
]
